# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RFishpond(RPackage):
	"""Fishpond: downstream methods and tools for expression data

	Fishpond contains methods for differential transcript and gene expression analysis of RNA-seq data using inferential replicates for uncertainty of abundance quantification, as generated by Gibbs sampling or bootstrap sampling. Also the package contains a number of utilities for working with Salmon and Alevin quantification files.
	"""
	
	homepage = "https://thelovelab.github.io/fishpond"
	bioc = "fishpond" 
	urls = ["https://www.bioconductor.org/packages/3.18/bioc/src/contrib/fishpond_2.8.0.tar.gz", "https://www.bioconductor.org/packages/3.18/bioc/src/contrib/Archive/fishpond/fishpond_2.8.0.tar.gz"]

	version("2.14.0", tag="RELEASE_3_21")
	version("2.8.0", sha256="9fedcbf9f3720cb52932a0cd7608bd0de0892922fdcc4ee0a9f0fd082e237413")

	depends_on("r-abind", type=("build", "run"))
	depends_on("r-gtools", type=("build", "run"))
	depends_on("r-qvalue", type=("build", "run"))
	depends_on("r-s4vectors", type=("build", "run"))
	depends_on("r-iranges", type=("build", "run"))
	depends_on("r-summarizedexperiment", type=("build", "run"))
	depends_on("r-genomicranges", type=("build", "run"))
	depends_on("r-matrixstats", type=("build", "run"))
	depends_on("r-svmisc", type=("build", "run"))
	depends_on("r-matrix", type=("build", "run"))
	depends_on("r-singlecellexperiment", type=("build", "run"))
	depends_on("r-jsonlite", type=("build", "run"))
