# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RSpicyworkflow(RPackage):
    """Performing a Spatial Analysis of Multiplexed Tissue Imaging Data

    We have developed an analytical framework for analysing data from high dimensional in situ cytometry assays including CODEX, CycIF, IMC and High Definition Spatial Transcriptomics. This framework makes use of functionality from our Bioconductor packages spicyR, lisaClust, scFeatures, FuseSOM, simpleSeg and ClassifyR and contains most of the key steps which are needed to interrogate the comprehensive spatial information generated by these exciting new technologies including cell segmentation, feature normalisation, cell type identification, micro-environment characterisation, spatial hypothesis testing and patient classification. Ultimately, our modular analysis framework provides a cohesive and accessible entry point into spatially resolved single cell data analysis for any R-based bioinformatician.
    """

    homepage = "https://github.com/SydneyBioX/spicyWorkflow"
    bioc = "spicyWorkflow"

    version("1.8.0", commit="2acaa1cee8e058037bdbc1af0fd0ff43646e6aa2")
    version("1.2.1", commit="9c22e3fc16eed182be288ddc659fd5f0aa03e7f8")

    depends_on("r@4.3:", type=("build", "run"))
