# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RArpobservation(RPackage):
	"""Tools for Simulating Direct Behavioral Observation Recording
Procedures Based on Alternating Renewal Processes

	Tools for simulating data generated by direct observation
    recording. Behavior streams are simulated based on an alternating renewal
    process, given specified distributions of event durations and interim
    times. Different procedures for recording data can then be applied to the
    simulated behavior streams. Functions are provided for the following
    recording methods: continuous duration recording, event counting, momentary
    time sampling, partial interval recording, whole interval recording, and
    augmented interval recording.
	"""
	
	cran = "ARPobservation" 

	version("1.2.2", md5="b1c02e89ef79019904d680909f4236bd")

