# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RCamera(RPackage):
	"""Collection of annotation related methods for mass spectrometry data

	Annotation of peaklists generated by xcms, rule based annotation of isotopes and adducts, isotope validation, EIC correlation based tagging of unknown adducts and fragments
	"""
	
	homepage = "http://msbi.ipb-halle.de/msbi/CAMERA/"
	bioc = "CAMERA" 
	urls = ["https://www.bioconductor.org/packages/release/bioc/src/contrib/CAMERA_1.58.0.tar.gz", "https://www.bioconductor.org/packages/release/bioc/src/contrib/Archive/CAMERA/CAMERA_1.58.0.tar.gz"]

	version("1.58.0", md5="1958cafb2c9dd92fa44a35cfc607f894")

	depends_on("r@3.5:", type=("build", "run"))
	depends_on("r-biobase", type=("build", "run"))
	depends_on("r-xcms", type=("build", "run"))
	depends_on("r-rbgl", type=("build", "run"))
	depends_on("r-graph", type=("build", "run"))
	depends_on("r-hmisc", type=("build", "run"))
	depends_on("r-igraph", type=("build", "run"))
