# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RLymphoseq(RPackage):
	"""Analyze high-throughput sequencing of T and B cell receptors

	This R package analyzes high-throughput sequencing of T and B cell receptor complementarity determining region 3 (CDR3) sequences generated by Adaptive Biotechnologies' ImmunoSEQ assay.  Its input comes from tab-separated value (.tsv) files exported from the ImmunoSEQ analyzer.
	"""
	
	bioc = "LymphoSeq" 
	urls = ["https://www.bioconductor.org/packages/3.18/bioc/src/contrib/LymphoSeq_1.30.0.tar.gz", "https://www.bioconductor.org/packages/3.18/bioc/src/contrib/Archive/LymphoSeq/LymphoSeq_1.30.0.tar.gz"]

	version("1.30.0", sha256="82bc329005677c11f6f36107c3ca1bc5b9b215860270206cce981cd15cd0e6a1")

	depends_on("r@3.3:", type=("build", "run"))
	depends_on("r-lymphoseqdb", type=("build", "run"))
	depends_on("r-data-table", type=("build", "run"))
	depends_on("r-plyr", type=("build", "run"))
	depends_on("r-dplyr", type=("build", "run"))
	depends_on("r-reshape", type=("build", "run"))
	depends_on("r-venndiagram", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-ineq", type=("build", "run"))
	depends_on("r-rcolorbrewer", type=("build", "run"))
	depends_on("r-circlize", type=("build", "run"))
	depends_on("r-ggtree", type=("build", "run"))
	depends_on("r-msa", type=("build", "run"))
	depends_on("r-biostrings", type=("build", "run"))
	depends_on("r-phangorn", type=("build", "run"))
	depends_on("r-stringdist", type=("build", "run"))
	depends_on("r-upsetr", type=("build", "run"))
