# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RLymphoseq(RPackage):
	"""Analyze high-throughput sequencing of T and B cell receptors

	This R package analyzes high-throughput sequencing of T and B cell receptor complementarity determining region 3 (CDR3) sequences generated by Adaptive Biotechnologies' ImmunoSEQ assay.  Its input comes from tab-separated value (.tsv) files exported from the ImmunoSEQ analyzer.
	"""
	
	bioc = "LymphoSeq"

	version("1.36.0", commit="e09579f4d87f2873db33bcd62d02db6038a72038")
	version("1.30.0", commit="a2049d8adafa0e0c0f3c8e39580c33e04c3c5da0")

	depends_on("r@3.3:", type=("build", "run"))
	depends_on("r-lymphoseqdb", type=("build", "run"))
	depends_on("r-data-table", type=("build", "run"))
	depends_on("r-plyr", type=("build", "run"))
	depends_on("r-dplyr", type=("build", "run"))
	depends_on("r-reshape", type=("build", "run"))
	depends_on("r-venndiagram", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-ineq", type=("build", "run"))
	depends_on("r-rcolorbrewer", type=("build", "run"))
	depends_on("r-circlize", type=("build", "run"))
	depends_on("r-ggtree", type=("build", "run"))
	depends_on("r-msa", type=("build", "run"))
	depends_on("r-biostrings", type=("build", "run"))
	depends_on("r-phangorn", type=("build", "run"))
	depends_on("r-stringdist", type=("build", "run"))
	depends_on("r-upsetr", type=("build", "run"))
