# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RRspde(RPackage):
	"""Rational Approximations of Fractional Stochastic Partial
Differential Equations

	Functions that compute rational approximations of fractional elliptic stochastic partial differential equations. The package also contains functions for common statistical usage of these approximations. The main references for rSPDE are Bolin, Simas and Xiong (2023) <doi:10.1080/10618600.2023.2231051> for the covariance-based method and Bolin and Kirchner (2020) <doi:10.1080/10618600.2019.1665537> for the operator-based rational approximation. These can be generated by the citation function in R.
	"""
	
	homepage = "https://davidbolin.github.io/rSPDE/"
	cran = "rSPDE" 

	version("2.3.3", md5="e5f0b4b44e6d66df1185d5fe8cd5a00f")

	depends_on("r@3.5:", type=("build", "run"))
	depends_on("r-matrix", type=("build", "run"))
	depends_on("r-fmesher", type=("build", "run"))
	depends_on("r-lifecycle", type=("build", "run"))
	depends_on("r-broom", type=("build", "run"))
