repos:
  - repo: local
    hooks:
      - id: spack-find-changed-packages
        name: Validate changed Spack packages via 'spack find'
        entry: githooks/spack-validate-changed-packages.sh
        language: system
        files: ^packages/
        pass_filenames: true
        stages: [pre-commit]
        env:
          SPACK_CMD: "singularity run --bind /usr/bin/zsh --bind /mnt/data /home/ubuntu/spack.sif"


