# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class REyelinkreader(RPackage):
	"""Import Gaze Data for EyeLink Eye Tracker

	Import gaze data from  edf files generated by 
  the SR Research <https://www.sr-research.com/> EyeLink eye tracker. Gaze data,
  both recorded events and samples, is imported per trial. The package allows to extract
  events of interest, such as saccades, blinks, etc. as well as
  recorded variables and custom events (areas of interest, triggers) into separate tables.
  The package requires EDF API library that can be obtained at <https://www.sr-research.com/support/>.
	"""
	
	homepage = "https://github.com/alexander-pastukhov/eyelinkReader/"
	cran = "eyelinkReader" 

	version("1.0.1", md5="c2b22093785bceb3d8c3cca4dea95624")

	depends_on("r@4.1:", type=("build", "run"))
	depends_on("r-rcppprogress", type=("build", "run"))
	depends_on("r-rlang", type=("build", "run"))
	depends_on("r-dplyr", type=("build", "run"))
	depends_on("r-fs", type=("build", "run"))
	depends_on("r-rcpp", type=("build", "run"))
	depends_on("r-stringr", type=("build", "run"))
	depends_on("r-tidyr", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
