# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RR4couchdb(RPackage):
	"""A R Convenience Layer for CouchDB 2.0

	Provides a collection of functions for basic
    database and document management operations such as add, get, list access
    or delete. Every cdbFunction() gets and returns a list() containing the
    connection setup. Such a list can be generated by cdbIni().
	"""
	
	homepage = "https://github.com/wactbprot/R4CouchDB"
	cran = "R4CouchDB" 

	version("0.7.5", md5="07be5f179c5c828a517473a2c0441587")

	depends_on("r@2.7:", type=("build", "run"))
	depends_on("r-bitops", type=("build", "run"))
	depends_on("r-rcurl@1.95:", type=("build", "run"))
	depends_on("r-rjsonio@1.3:", type=("build", "run"))
