# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RMaser(RPackage):
    """Mapping Alternative Splicing Events to pRoteins

    This package provides functionalities for downstream analysis, annotation and visualizaton of alternative splicing events generated by rMATS.
    """

    homepage = "https://github.com/DiogoVeiga/maser"
    bioc = "maser"

    version("1.26.0", commit="2a9cfaf63ea4bd1349fa786b65c4d57b1e352c47")
    version("1.20.0", commit="2ed0e4a56bfaf208fd2e02b898bd322e313c28c7")

    depends_on("r@3.5:", type=("build", "run"))
    depends_on("r-ggplot2", type=("build", "run"))
    depends_on("r-genomicranges", type=("build", "run"))
    depends_on("r-dplyr", type=("build", "run"))
    depends_on("r-rtracklayer", type=("build", "run"))
    depends_on("r-reshape2", type=("build", "run"))
    depends_on("r-gviz", type=("build", "run"))
    depends_on("r-dt", type=("build", "run"))
    depends_on("r-genomeinfodb", type=("build", "run"))
    depends_on("r-iranges", type=("build", "run"))
    depends_on("r-biocgenerics", type=("build", "run"))
    depends_on("r-data-table", type=("build", "run"))
