# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RScreclassify(RPackage):
	"""scReClassify: post hoc cell type classification of single-cell RNA-seq data

	A post hoc cell type classification tool to fine-tune cell type annotations generated by any cell type classification procedure with semi-supervised learning algorithm AdaSampling technique. The current version of scReClassify supports Support Vector Machine and Random Forest as a base classifier.
	"""
	
	homepage = "https://github.com/SydneyBioX/scReClassify"
	bioc = "scReClassify" 
	urls = ["https://www.bioconductor.org/packages/3.18/bioc/src/contrib/scReClassify_1.8.0.tar.gz", "https://www.bioconductor.org/packages/3.18/bioc/src/contrib/Archive/scReClassify/scReClassify_1.8.0.tar.gz"]

	version("1.8.0", md5="722bce944db1f380df35d68a47c4bef7")

	depends_on("r@4.1:", type=("build", "run"))
	depends_on("r-randomforest", type=("build", "run"))
	depends_on("r-e1071", type=("build", "run"))
	depends_on("r-summarizedexperiment", type=("build", "run"))
	depends_on("r-singlecellexperiment", type=("build", "run"))
