# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RTracerer(RPackage):
	"""Tracer from R

	'BEAST2' (<https://www.beast2.org>) is a widely used
  Bayesian phylogenetic tool, that uses DNA/RNA/protein data
  and many model priors to create a posterior of jointly estimated 
  phylogenies and parameters.
  'Tracer' (<https://github.com/beast-dev/tracer/>) is a GUI tool 
  to parse and analyze the files generated by 'BEAST2'.
  This package provides a way to parse and analyze 'BEAST2' input
  files without active user input, but using
  R function calls instead.
	"""
	
	homepage = "https://docs.ropensci.org/tracerer/"
	cran = "tracerer" 

	version("2.2.3", md5="0f7c578646e25b44b0e6cf3094d74dc3")

	depends_on("r-jsonlite", type=("build", "run"))
	depends_on("r-rcpp", type=("build", "run"))
	depends_on("r-testit", type=("build", "run"))
