# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RDepmap(RPackage):
    """Cancer Dependency Map Data Package

    The depmap package is a data package that accesses datsets from the Broad Institute DepMap cancer dependency study using ExperimentHub. Datasets from the most current release are available, including RNAI and CRISPR-Cas9 gene knockout screens quantifying the genetic dependency for select cancer cell lines. Additional datasets are also available pertaining to the log copy number of genes for select cell lines, protein expression of cell lines as measured by reverse phase protein lysate microarray (RPPA), 'Transcript Per Million' (TPM) data, as well as supplementary datasets which contain metadata and mutation calls for the other datasets found in the current release. The 19Q3 release adds the drug_dependency dataset, that contains cancer cell line dependency data with respect to drug and drug-candidate compounds. The 20Q2 release adds the proteomic dataset that contains quantitative profiling of proteins via mass spectrometry. This package will be updated on a quarterly basis to incorporate the latest Broad Institute DepMap Public cancer dependency datasets. All data made available in this package was generated by the Broad Institute DepMap for research purposes and not intended for clinical use. This data is distributed under the Creative Commons license (Attribution 4.0 International (CC BY 4.0)).
    """

    bioc = "depmap"

    version("1.22.0", commit="51c2846fcca9650ff90bde227efb5191490b1d3c")
    version("1.16.0", commit="e8988f93fbe8fc477ff662f092c68a8ceabcfca8")

    depends_on("r@3.6:", type=("build", "run"))
    depends_on("r-dplyr", type=("build", "run"))
    depends_on("r-experimenthub", type=("build", "run"))
    depends_on("r-annotationhub", type=("build", "run"))
