# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RTenxbraindata(RPackage):
	"""Data from the 10X 1.3 Million Brain Cell Study

	Single-cell RNA-seq data for 1.3 million brain cells from E18 mice, generated by 10X Genomics.
	"""
	
	bioc = "TENxBrainData"

	version("1.28.0", commit="314de8a01c22c8310c74b0fe148c51436594ffca")
	version("1.22.0", commit="2b732db8ffb340a2230ea51d41f2a701be22ab92")

	depends_on("r-singlecellexperiment", type=("build", "run"))
	depends_on("r-hdf5array", type=("build", "run"))
	depends_on("r-annotationhub@2.9.22:", type=("build", "run"))
	depends_on("r-experimenthub", type=("build", "run"))

