# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RSafari(RPackage):
	"""Shape Analysis for AI-Reconstructed Images

	Provides functionality for image processing and shape analysis in 
    the context of reconstructed medical images generated by deep learning-based
    methods or standard image processing algorithms and produced from different
    medical imaging types, such as X-ray, Computational Tomography (CT),
    Magnetic Resonance Imaging (MRI), and pathology imaging. Specifically,
    offers tools to segment regions of interest and to extract quantitative
    shape descriptors for applications in signal processing,
    statistical analysis and modeling, and machine learning.
	"""
	
	homepage = "https://github.com/estfernandez/SAFARI"
	cran = "SAFARI" 

	version("0.1.0", md5="16fcecc6cb3fafdc0acd0e2734069af1")

	depends_on("r@3.5:", type=("build", "run"))
	depends_on("r-catools", type=("build", "run"))
	depends_on("r-ebimage", type=("build", "run"))
	depends_on("r-lattice", type=("build", "run"))
	depends_on("r-png", type=("build", "run"))
