# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RHcatonsildata(RPackage):
	"""Provide programmatic access to the tonsil cell atlas datasets

	This package provides access to the scRNA-seq, scATAC-seq, multiome, CITE-seq and spatial transcriptomics (Visium) data generated by the tonsil cell atlas in the context of the Human Cell Atlas (HCA). The data is provided via the Bioconductor project in the form of SingleCellExperiments. Additionally, information on the whole compendium of identified cell types is provided in form of a glossary.
	"""
	
	homepage = "https://github.com/massonix/HCATonsilData"
	bioc = "HCATonsilData"

	version("1.6.0", commit="a4e7b4b8ac75300adf1c8791949f17ed1c8e165a")
	version("1.0.0", commit="6f017074b3525f74ca49e83bfcf43e96af7015ad")

	depends_on("r@4.3:", type=("build", "run"))
	depends_on("r-experimenthub", type=("build", "run"))
	depends_on("r-singlecellexperiment", type=("build", "run"))
	depends_on("r-spatialexperiment", type=("build", "run"))
	depends_on("r-hdf5array", type=("build", "run"))
	depends_on("r-summarizedexperiment", type=("build", "run"))
	depends_on("r-s4vectors", type=("build", "run"))
	depends_on("r-htmltools", type=("build", "run"))
	depends_on("r-rmarkdown", type=("build", "run"))
	depends_on("r-base64enc", type=("build", "run"))

