# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RFlowpeaks(RPackage):
	"""An R package for flow data clustering

	A fast and automatic clustering to classify the cells into subpopulations based on finding the peaks from the overall density function generated by K-means.
	"""
	
	bioc = "flowPeaks" 
	urls = ["https://www.bioconductor.org/packages/3.18/bioc/src/contrib/flowPeaks_1.48.0.tar.gz", "https://www.bioconductor.org/packages/3.18/bioc/src/contrib/Archive/flowPeaks/flowPeaks_1.48.0.tar.gz"]

    version("1.54.0", tag="RELEASE_3_21")
	version("1.48.0", sha256="84baaf3c7e8c2cd9790dfd086bf56ce07d448be6255285330dfc92b0b2fafafb")

	depends_on("r@2.12:", type=("build", "run"))
	depends_on("gsl", type=("build", "link", "run"))
