# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RFlowpeaks(RPackage):
    """An R package for flow data clustering

    A fast and automatic clustering to classify the cells into subpopulations based on finding the peaks from the overall density function generated by K-means.
    """

    bioc = "flowPeaks"

    version("1.54.0", commit="d480f04af0ed79e2ef439d2a705925fedfdea3b6")
    version("1.48.0", commit="d5033623c31715965ddb22904fb7ae0863482576")

    depends_on("r@2.12:", type=("build", "run"))
    depends_on("gsl", type=("build", "link", "run"))
