# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class REnrichviewnet(RPackage):
	"""From functional enrichment results to biological networks

	This package enables the visualization of functional enrichment results as network graphs. First the package enables the visualization of enrichment results, in a format corresponding to the one generated by gprofiler2, as a customizable Cytoscape network. In those networks, both gene datasets (GO terms/pathways/protein complexes) and genes associated to the datasets are represented as nodes. While the edges connect each gene to its dataset(s). The package also provides the option to create enrichment maps from functional enrichment results. Enrichment maps enable the visualization of enriched terms into a network with edges connecting overlapping genes.
	"""
	
	homepage = "https://github.com/adeschen/enrichViewNet"
	bioc = "enrichViewNet" 
	urls = ["https://www.bioconductor.org/packages/3.18/bioc/src/contrib/enrichViewNet_1.0.0.tar.gz", "https://www.bioconductor.org/packages/3.18/bioc/src/contrib/Archive/enrichViewNet/enrichViewNet_1.0.0.tar.gz"]

	version("1.6.0", tag="RELEASE_3_21")
	version("1.0.0", sha256="9b7bdd6591da9e94251ed4599287814b53ccae5eeace8c5fd689e9818160e510")

	depends_on("r@4.2:", type=("build", "run"))
	depends_on("r-gprofiler2", type=("build", "run"))
	depends_on("r-strex", type=("build", "run"))
	depends_on("r-rcy3", type=("build", "run"))
	depends_on("r-jsonlite", type=("build", "run"))
	depends_on("r-stringr", type=("build", "run"))
	depends_on("r-enrichplot", type=("build", "run"))
