# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RTenxpbmcdata(RPackage):
	"""PBMC data from 10X Genomics

	Single-cell RNA-seq data for on PBMC cells, generated by 10X Genomics.
	"""
	
	bioc = "TENxPBMCData"

	version("1.26.0", commit="f213307aeedc53b402dad0b5c54164320ebeeaf9")
	version("1.20.0", commit="0039287c42470669d53ad80c358dec15c1f5a44f")

	depends_on("r-singlecellexperiment", type=("build", "run"))
	depends_on("r-hdf5array", type=("build", "run"))
	depends_on("r-annotationhub", type=("build", "run"))
	depends_on("r-experimenthub", type=("build", "run"))

