# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RMeskit(RPackage):
	"""A tool kit for dissecting cancer evolution from multi-region derived tumor biopsies via somatic alterations

	MesKit provides commonly used analysis and visualization modules based on mutational data generated by multi-region sequencing (MRS). This package allows to depict mutational profiles, measure heterogeneity within or between tumors from the same patient, track evolutionary dynamics, as well as characterize mutational patterns on different levels. Shiny application was also developed for a need of GUI-based analysis. As a handy tool, MesKit can facilitate the interpretation of tumor heterogeneity and the understanding of evolutionary relationship between regions in MRS study.
	"""
	
	bioc = "MesKit" 
	urls = ["https://www.bioconductor.org/packages/release/bioc/src/contrib/MesKit_1.12.0.tar.gz", "https://www.bioconductor.org/packages/release/bioc/src/contrib/Archive/MesKit/MesKit_1.12.0.tar.gz"]

	version("1.12.0", md5="909ad92f34384c66c0e86f0f13ff7e71")

	depends_on("r@4:", type=("build", "run"))
	depends_on("r-data-table", type=("build", "run"))
	depends_on("r-biostrings", type=("build", "run"))
	depends_on("r-dplyr", type=("build", "run"))
	depends_on("r-tidyr@1:", type=("build", "run"))
	depends_on("r-ape@5.4.1:", type=("build", "run"))
	depends_on("r-ggrepel", type=("build", "run"))
	depends_on("r-pracma", type=("build", "run"))
	depends_on("r-ggridges", type=("build", "run"))
	depends_on("r-annotationdbi", type=("build", "run"))
	depends_on("r-iranges", type=("build", "run"))
	depends_on("r-circlize", type=("build", "run"))
	depends_on("r-cowplot", type=("build", "run"))
	depends_on("r-mclust", type=("build", "run"))
	depends_on("r-phangorn", type=("build", "run"))
	depends_on("r-complexheatmap@1.9.3:", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-rcolorbrewer", type=("build", "run"))
	depends_on("r-s4vectors", type=("build", "run"))
