# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RHicontactsdata(RPackage):
    """HiContacts companion data package

    Provides a collection of Hi-C files (pairs, (m)cool and fastq). These datasets can be read into R and further investigated and visualized with the HiContacts package. Data includes yeast Hi-C data generated by the Koszul lab from the Pasteur Institute.
    """

    homepage = "https://github.com/js2264/HiContactsData"
    bioc = "HiContactsData"

    version("1.10.0", commit="ff4382477ab706e3af0be5a4b48ab1b03fc0a84a")
    version("1.4.0", commit="bdbf11541e896f9017fbc173b2b7bff7b7c4b6f5")

    depends_on("r-experimenthub", type=("build", "run"))
    depends_on("r-biocfilecache", type=("build", "run"))
    depends_on("r-annotationhub", type=("build", "run"))
