# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RHicontactsdata(RPackage):
	"""HiContacts companion data package

	Provides a collection of Hi-C files (pairs, (m)cool and fastq). These datasets can be read into R and further investigated and visualized with the HiContacts package. Data includes yeast Hi-C data generated by the Koszul lab from the Pasteur Institute.
	"""
	
	homepage = "https://github.com/js2264/HiContactsData"
	bioc = "HiContactsData" 
	urls = ["https://www.bioconductor.org/packages/3.18/data/experiment/src/contrib/HiContactsData_1.4.0.tar.gz", "https://www.bioconductor.org/packages/3.18/data/experiment/src/contrib/Archive/HiContactsData/HiContactsData_1.4.0.tar.gz"]

    version("1.10.0", tag="RELEASE_3_21")
	version("1.4.0", sha256="f1f4acf52f10be3093fad7a8d674a648d656c7648f67b9f811cfd8757e0e291e")

	depends_on("r-experimenthub", type=("build", "run"))
	depends_on("r-biocfilecache", type=("build", "run"))
	depends_on("r-annotationhub", type=("build", "run"))

