# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RHicontactsdata(RPackage):
	"""HiContacts companion data package

	Provides a collection of Hi-C files (pairs, (m)cool and fastq). These datasets can be read into R and further investigated and visualized with the HiContacts package. Data includes yeast Hi-C data generated by the Koszul lab from the Pasteur Institute.
	"""
	
	homepage = "https://github.com/js2264/HiContactsData"
	bioc = "HiContactsData" 
	urls = ["https://www.bioconductor.org/packages/release/data/experiment/src/contrib/HiContactsData_1.4.0.tar.gz", "https://www.bioconductor.org/packages/release/data/experiment/src/contrib/Archive/HiContactsData/HiContactsData_1.4.0.tar.gz"]

	version("1.4.0", md5="bcd518f48342168f7a814a442cf9564c")

	depends_on("r-experimenthub", type=("build", "run"))
	depends_on("r-biocfilecache", type=("build", "run"))
	depends_on("r-annotationhub", type=("build", "run"))

	# experiment