# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RRtnduals(RPackage):
	"""Analysis of co-regulation and inference of 'dual regulons'

	RTNduals is a tool that searches for possible co-regulatory loops between regulon pairs generated by the RTN package. It compares the shared targets in order to infer 'dual regulons', a new concept that tests whether regulators can co-operate or compete in influencing targets.
	"""
	
	bioc = "RTNduals"

	version("1.32.0", commit="dcd82a6d45a14ece9eaacd3a048c9f480124598b")
	version("1.26.0", commit="67ab781a069d5bdfa23e6db899aa9e1e80aa52d2")

	depends_on("r@3.6.3:", type=("build", "run"))
	depends_on("r-rtn@2.14.1:", type=("build", "run"))
