# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RRtnduals(RPackage):
	"""Analysis of co-regulation and inference of 'dual regulons'

	RTNduals is a tool that searches for possible co-regulatory loops between regulon pairs generated by the RTN package. It compares the shared targets in order to infer 'dual regulons', a new concept that tests whether regulators can co-operate or compete in influencing targets.
	"""
	
	bioc = "RTNduals" 
	urls = ["https://www.bioconductor.org/packages/3.18/bioc/src/contrib/RTNduals_1.26.0.tar.gz", "https://www.bioconductor.org/packages/3.18/bioc/src/contrib/Archive/RTNduals/RTNduals_1.26.0.tar.gz"]

    version("1.32.0", tag="RELEASE_3_21")
	version("1.26.0", sha256="114914e883b679a2ac12505adeb58cc2ea3219457794bc682095247a0628282a")

	depends_on("r@3.6.3:", type=("build", "run"))
	depends_on("r-rtn@2.14.1:", type=("build", "run"))
