# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RSemmcci(RPackage):
	"""Monte Carlo Confidence Intervals in Structural Equation Modeling

	Monte Carlo confidence intervals for free and defined parameters
    in models fitted in the structural equation modeling package 'lavaan'
    can be generated using the 'semmcci' package.
    'semmcci' has three main functions, namely, MC(), MCMI(), and MCStd().
    The output of 'lavaan' is passed as the first argument
    to the MC() function or the MCMI() function to generate Monte Carlo confidence intervals.
    Monte Carlo confidence intervals for the standardized estimates
    can also be generated by passing the output of the MC() function or the MCMI() function
    to the MCStd() function.
    A description of the package and code examples
    are presented in Pesigan and Cheung (2023) <doi:10.3758/s13428-023-02114-4>.
	"""
	
	homepage = "https://github.com/jeksterslab/semmcci"
	cran = "semmcci" 

	version("1.1.4", md5="e73b1d88352cf92816dad09e50244e77")

	depends_on("r@3:", type=("build", "run"))
	depends_on("r-lavaan", type=("build", "run"))
	depends_on("r-mice", type=("build", "run"))
