# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RRobustvarcomp(RPackage):
	"""Robust Estimation of Variance Component Models

	Robust Estimation of Variance Component Models by classic and composite robust procedures. The composite procedures are robust against outliers generated by the Independent Contamination Model.  
	"""
	
	cran = "robustvarComp" 

	version("0.1-7", md5="ac3826ca52962c43d4840fb709288e64")

	depends_on("r@2.15.1:", type=("build", "run"))
	depends_on("r-robustbase", type=("build", "run"))
	depends_on("r-gse", type=("build", "run"))
	depends_on("r-numderiv", type=("build", "run"))
	depends_on("r-robust", type=("build", "run"))
	depends_on("r-plyr", type=("build", "run"))
