# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RCountfitter(RPackage):
	"""Comprehensive Automatized Evaluation of Distribution Models for
Count Data

	A large number of measurements generate count data. This is a statistical data type 
    that only assumes non-negative integer values and is generated by counting. Typically, counting 
    data can be found in biomedical applications, such as the analysis of DNA double-strand breaks. 
    The number of DNA double-strand breaks can be counted in individual cells using various 
    bioanalytical methods. For diagnostic applications, it is relevant to record the distribution of 
    the number data in order to determine their biomedical significance (Roediger, S. et al., 2018. 
    Journal of Laboratory and Precision Medicine. <doi:10.21037/jlpm.2018.04.10>). The software 
    offers functions for a comprehensive automated evaluation of distribution models of count 
    data. In addition to programmatic interaction, a graphical user interface (web server) 
    is included, which enables fast and interactive data-scientific analyses. The user is supported 
    in selecting the most suitable counting distribution for his own data set.
	"""
	
	homepage = "https://github.com/BioGenies/countfitteR"
	cran = "countfitteR" 

	version("1.4", md5="be9212fe5db358bf576501e0cdffc05f")

	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-mass", type=("build", "run"))
	depends_on("r-shiny", type=("build", "run"))
	depends_on("r-pscl", type=("build", "run"))
