# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RUsfertilizer(RPackage):
	"""County-Level Estimates of Fertilizer Application in USA

	Compiled and cleaned the county-level estimates of fertilizer, 
    nitrogen and phosphorus, from 1945 to 2012 in United States of America (USA).  The commercial fertilizer data were originally 
    generated by USGS based on the sales data of commercial fertilizer. The manure data were estimated
    based on county-level population data of livestock, poultry, and other animals.
    See the user manual for detailed data sources and cleaning methods.  
    'usfertilizer' utilized the tidyverse to clean the original data and provide 
    user-friendly dataframe. Please note that USGS does not endorse this package. Also data from 1986 is not available for now.
	"""
	
	homepage = "https://github.com/wenlong-liu/usfertilizer"
	cran = "usfertilizer" 

	version("0.1.5", md5="7402d3fa9b978bba0b29bea48d89aa3c")

	depends_on("r@2.10:", type=("build", "run"))
	depends_on("r-tidyverse", type=("build", "run"))
