# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RRtcga(RPackage):
	"""The Cancer Genome Atlas Data Integration

	The Cancer Genome Atlas (TCGA) Data Portal provides a platform for researchers to search, download, and analyze data sets generated by TCGA. It contains clinical information, genomic characterization data, and high level sequence analysis of the tumor genomes. The key is to understand genomics to improve cancer care. RTCGA package offers download and integration of the variety and volume of TCGA data using patient barcode key, what enables easier data possession. This may have an benefcial infuence on impact on development of science and improvement of patients' treatment. Furthermore, RTCGA package transforms TCGA data to tidy form which is convenient to use.
	"""
	
	homepage = "https://rtcga.github.io/RTCGA"
	bioc = "RTCGA" 
	urls = ["https://www.bioconductor.org/packages/3.18/bioc/src/contrib/RTCGA_1.32.0.tar.gz", "https://www.bioconductor.org/packages/3.18/bioc/src/contrib/Archive/RTCGA/RTCGA_1.32.0.tar.gz"]

	version("1.32.0", md5="97f413704d77f40ecbe00a1e0d25602d")

	depends_on("r@3.3:", type=("build", "run"))
	depends_on("r-xml", type=("build", "run"))
	depends_on("r-rcurl", type=("build", "run"))
	depends_on("r-assertthat", type=("build", "run"))
	depends_on("r-stringi", type=("build", "run"))
	depends_on("r-rvest", type=("build", "run"))
	depends_on("r-data-table", type=("build", "run"))
	depends_on("r-xml2", type=("build", "run"))
	depends_on("r-dplyr", type=("build", "run"))
	depends_on("r-purrr", type=("build", "run"))
	depends_on("r-survival", type=("build", "run"))
	depends_on("r-survminer", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-ggthemes", type=("build", "run"))
	depends_on("r-viridis", type=("build", "run"))
	depends_on("r-knitr", type=("build", "run"))
	depends_on("r-scales", type=("build", "run"))
	depends_on("r-rmarkdown", type=("build", "run"))
	depends_on("r-htmltools", type=("build", "run"))
