# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RCytoviewer(RPackage):
	"""An interactive multi-channel image viewer for R

	This R package supports interactive visualization of multi-channel images and segmentation masks generated by imaging mass cytometry and other highly multiplexed imaging techniques using shiny. The cytoviewer interface is divided into image-level (Composite and Channels) and cell-level visualization (Masks). It allows users to overlay individual images with segmentation masks, integrates well with SingleCellExperiment and SpatialExperiment objects for metadata visualization and supports image downloads.
	"""
	
	homepage = "https://github.com/BodenmillerGroup/cytoviewer"
	bioc = "cytoviewer"

	version("1.8.0", commit="b675a1cc9e7d661bf9c0c28230a333b7e76a9f9f")
	version("1.2.0", commit="96bf9c6c2b6919bfb9a171d26240688492b84dd5")

	depends_on("r-shiny", type=("build", "run"))
	depends_on("r-shinydashboard", type=("build", "run"))
	depends_on("r-colourpicker", type=("build", "run"))
	depends_on("r-shinycssloaders", type=("build", "run"))
	depends_on("r-svgpanzoom", type=("build", "run"))
	depends_on("r-viridis", type=("build", "run"))
	depends_on("r-archive", type=("build", "run"))
	depends_on("r-rcolorbrewer", type=("build", "run"))
	depends_on("r-svglite", type=("build", "run"))
	depends_on("r-ebimage", type=("build", "run"))
	depends_on("r-cytomapper", type=("build", "run"))
	depends_on("r-singlecellexperiment", type=("build", "run"))
	depends_on("r-s4vectors", type=("build", "run"))
	depends_on("r-summarizedexperiment", type=("build", "run"))
