# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RCytoviewer(RPackage):
	"""An interactive multi-channel image viewer for R

	This R package supports interactive visualization of multi-channel images and segmentation masks generated by imaging mass cytometry and other highly multiplexed imaging techniques using shiny. The cytoviewer interface is divided into image-level (Composite and Channels) and cell-level visualization (Masks). It allows users to overlay individual images with segmentation masks, integrates well with SingleCellExperiment and SpatialExperiment objects for metadata visualization and supports image downloads.
	"""
	
	homepage = "https://github.com/BodenmillerGroup/cytoviewer"
	bioc = "cytoviewer" 
	urls = ["https://www.bioconductor.org/packages/3.18/bioc/src/contrib/cytoviewer_1.2.0.tar.gz", "https://www.bioconductor.org/packages/3.18/bioc/src/contrib/Archive/cytoviewer/cytoviewer_1.2.0.tar.gz"]

	version("1.8.0", tag="RELEASE_3_21")
	version("1.2.0", sha256="a82429120643e00d49ca9897b1eb3ecf477ae0c7cb0244d1a2fa828a8774676e")

	depends_on("r-shiny", type=("build", "run"))
	depends_on("r-shinydashboard", type=("build", "run"))
	depends_on("r-colourpicker", type=("build", "run"))
	depends_on("r-shinycssloaders", type=("build", "run"))
	depends_on("r-svgpanzoom", type=("build", "run"))
	depends_on("r-viridis", type=("build", "run"))
	depends_on("r-archive", type=("build", "run"))
	depends_on("r-rcolorbrewer", type=("build", "run"))
	depends_on("r-svglite", type=("build", "run"))
	depends_on("r-ebimage", type=("build", "run"))
	depends_on("r-cytomapper", type=("build", "run"))
	depends_on("r-singlecellexperiment", type=("build", "run"))
	depends_on("r-s4vectors", type=("build", "run"))
	depends_on("r-summarizedexperiment", type=("build", "run"))
