# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RCycle(RPackage):
	"""Significance of periodic expression pattern in time-series data

	Package for assessing the statistical significance of periodic expression based on Fourier analysis and comparison with data generated by different background models
	"""
	
	homepage = "http://cycle.sysbiolab.eu"
	bioc = "cycle" 
	urls = ["https://www.bioconductor.org/packages/release/bioc/src/contrib/cycle_1.56.0.tar.gz", "https://www.bioconductor.org/packages/release/bioc/src/contrib/Archive/cycle/cycle_1.56.0.tar.gz"]

	version("1.56.0", md5="8c659d2ae2fb2b31f4b6dd07d68873be")

	depends_on("r@2.10:", type=("build", "run"))
	depends_on("r-mfuzz", type=("build", "run"))
	depends_on("r-biobase", type=("build", "run"))
