# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RCycle(RPackage):
    """Significance of periodic expression pattern in time-series data

    Package for assessing the statistical significance of periodic expression based on Fourier analysis and comparison with data generated by different background models
    """

    homepage = "http://cycle.sysbiolab.eu"
    bioc = "cycle"

    version("1.62.0", commit="06788b1c201f151e73e6181503cd0244288ef304")
    version("1.56.0", commit="366b8d57ce089ba85457dd825583fd9dd720812c")

    depends_on("r@2.10:", type=("build", "run"))
    depends_on("r-mfuzz", type=("build", "run"))
    depends_on("r-biobase", type=("build", "run"))
