# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RIohanalyzer(RPackage):
	"""Data Analysis Part of 'IOHprofiler'

	The data analysis module for the Iterative Optimization Heuristics
    Profiler ('IOHprofiler'). This module provides statistical analysis methods for the 
    benchmark data generated by optimization heuristics, which can be visualized through a 
    web-based interface. The benchmark data is usually generated by the 
    experimentation module, called 'IOHexperimenter'. 'IOHanalyzer' also supports
    the widely used 'COCO' (Comparing Continuous Optimisers) data format for benchmarking.
	"""
	
	homepage = "https://iohanalyzer.liacs.nl"
	cran = "IOHanalyzer" 

	version("0.1.8.10", md5="64e685d76cec540692a8476c96eca694")

	depends_on("r@2.10:", type=("build", "run"))
	depends_on("r-magrittr", type=("build", "run"))
	depends_on("r-dplyr", type=("build", "run"))
	depends_on("r-data-table", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-plotly", type=("build", "run"))
	depends_on("r-colorspace", type=("build", "run"))
	depends_on("r-rcolorbrewer", type=("build", "run"))
	depends_on("r-shiny", type=("build", "run"))
	depends_on("r-reshape2", type=("build", "run"))
	depends_on("r-stringi", type=("build", "run"))
	depends_on("r-httr", type=("build", "run"))
	depends_on("r-knitr", type=("build", "run"))
	depends_on("r-rjson", type=("build", "run"))
	depends_on("r-eaf", type=("build", "run"))
	depends_on("r-viridis", type=("build", "run"))
	depends_on("r-rcpp", type=("build", "run"))
