# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class REcolmod(RPackage):
	""""A Practical Guide to Ecological Modelling - Using R as a
Simulation Platform"

	Figures, data sets and examples from the book "A practical guide to ecological modelling - using R as a simulation platform" by Karline Soetaert and Peter MJ Herman (2009). Springer.
  All figures from chapter x can be generated by "demo(chapx)", where x = 1 to 11. 
  The R-scripts of the model examples discussed in the book are in subdirectory "examples", ordered per chapter.
  Solutions to model projects are in the same subdirectories.
	"""
	
	cran = "ecolMod" 

	version("1.2.6.4", md5="67144feea3ca50589d6eff74d81a5269")

	depends_on("r@2.1:", type=("build", "run"))
	depends_on("r-rootsolve", type=("build", "run"))
	depends_on("r-shape", type=("build", "run"))
	depends_on("r-diagram", type=("build", "run"))
	depends_on("r-desolve", type=("build", "run"))
