# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RChippcr(RPackage):
	"""Toolkit of Helper Functions to Pre-Process Amplification Data

	A collection of functions to pre-process amplification curve data from polymerase chain reaction (PCR) or isothermal amplification reactions. Contains functions to normalize and baseline amplification curves, to detect both the start and end of an amplification reaction, several smoothers (e.g., LOWESS, moving average, cubic splines, Savitzky-Golay), a function to detect false positive amplification reactions and a function to determine the amplification efficiency. Quantification point (Cq) methods include the first (FDM) and second approximate derivative maximum (SDM) methods (calculated by a 5-point-stencil) and the cycle threshold method. Data sets of experimental nucleic acid amplification systems ('VideoScan HCU', capillary convective PCR (ccPCR)) and commercial systems are included. Amplification curves were generated by helicase dependent amplification (HDA), ccPCR or PCR. As detection system intercalating dyes (EvaGreen, SYBR Green) and hydrolysis probes (TaqMan) were used. For more information see: Roediger et al. (2015) <doi:10.1093/bioinformatics/btv205>. 
	"""
	
	homepage = "https://github.com/PCRuniversum/chipPCR"
	cran = "chipPCR" 

	version("1.0-2", md5="f00d8ad1745cbaee5a22d1944b0f0509")

	depends_on("r@3:", type=("build", "run"))
	depends_on("r-lmtest", type=("build", "run"))
	depends_on("r-mass", type=("build", "run"))
	depends_on("r-outliers", type=("build", "run"))
	depends_on("r-ptw", type=("build", "run"))
	depends_on("r-quantreg", type=("build", "run"))
	depends_on("r-rfit", type=("build", "run"))
	depends_on("r-robustbase", type=("build", "run"))
	depends_on("r-shiny", type=("build", "run"))
	depends_on("r-signal", type=("build", "run"))
