# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RTeda(RPackage):
	"""An Implementation of the Typicality and Eccentricity Data
Analysis Framework

	The typicality and eccentricity data analysis (TEDA) framework was
    put forward by Angelov (2013) <DOI:10.14313/JAMRIS_2-2014/16>. It has been further developed into multiple
    different techniques since, and provides a non-parametric way of determining how
    similar an observation, from a process that is not purely random, is to other
    observations generated by the process. This package provides code to use the
    batch and recursive TEDA methods that have been published.
	"""
	
	cran = "teda" 

	version("0.1.1", md5="2b8c922b457b50e3295f86f1f1415269")

