# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RRchronomodel(RPackage):
	"""Post-Processing of the Markov Chain Simulated by ChronoModel or
Oxcal

	Provides a list of functions for the statistical analysis and the post-processing of the Markov Chains simulated by ChronoModel (see <http://www.chronomodel.fr> for more information).  ChronoModel is a friendly software to construct a chronological model in a Bayesian framework.  Its output is  a sampled Markov chain from the posterior distribution of dates component  the chronology. The functions can also be applied  to the  analyse of mcmc output generated by Oxcal software.
	"""
	
	homepage = "http://www.chronomodel.fr"
	cran = "RChronoModel" 

	version("0.4", md5="657bb078abaf18567a2e3000f8cf7a40")

	depends_on("r@2.10:", type=("build", "run"))
	depends_on("r-hdrcde", type=("build", "run"))
