# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RLmerperm(RPackage):
	"""Perform Permutation Test on General Linear and Mixed Linear
Regression

	We provide a solution for performing permutation tests on linear and mixed linear regression models. It
             allows users to obtain accurate p-values without making distributional assumptions about the data. By 
             generating a null distribution of the test statistics through repeated permutations of the response variable,
             permutation tests provide a powerful alternative to traditional parameter tests (Holt et al. (2023) 
             <doi:10.1007/s10683-023-09799-6>). In this early version, we focus on the permutation tests over observed 
             t values of beta coefficients, i.e.original t values generated by parameter tests. After generating a null 
             distribution of the test statistic through repeated permutations of the response variable, each observed t 
             values would be compared to the null distribution to generate a p-value. To improve the efficiency,a stop 
             criterion (Anscombe (1953) <doi:10.1111/j.2517-6161.1953.tb00121.x>) is adopted to force permutation to stop 
             if the estimated standard deviation of the value falls below a fraction of the estimated p-value. By doing so,
             we avoid the need for massive calculations in exact permutation methods while still generating stable and accurate 
             p-values.
	"""
	
	cran = "lmerPerm" 

	version("0.1.9", md5="a07718b6b1e24d638b19d16238dd44d6")

	depends_on("r-lmertest", type=("build", "run"))
