# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RIraceplot(RPackage):
	"""Plots for Visualizing the Data Produced by the 'irace' Package

	Graphical visualization tools for analyzing the data produced by 'irace'. The 'iraceplot' package enables users to analyze the performance and the parameter space data sampled by the configuration during the search process. It provides a set of functions that generate different plots to visualize the configurations sampled during the execution of 'irace' and their performance. The functions just require the log file generated by 'irace' and, in some cases, they can be used with user-provided data.
	"""
	
	homepage = "https://auto-optimization.github.io/iraceplot/"
	cran = "iraceplot" 

	version("1.2", md5="e3dbc869a83208dd93851dc1c63d8e18")

	depends_on("r@3.4:", type=("build", "run"))
	depends_on("r-irace@3.5:", type=("build", "run"))
	depends_on("r-cli", type=("build", "run"))
	depends_on("r-dplyr", type=("build", "run"))
	depends_on("r-dt", type=("build", "run"))
	depends_on("r-forcats", type=("build", "run"))
	depends_on("r-ggforce", type=("build", "run"))
	depends_on("r-ggplot2@3.3.6:", type=("build", "run"))
	depends_on("r-gridextra", type=("build", "run"))
	depends_on("r-knitr", type=("build", "run"))
	depends_on("r-matrixstats@0.55:", type=("build", "run"))
	depends_on("r-plotly", type=("build", "run"))
	depends_on("r-rlang", type=("build", "run"))
	depends_on("r-rmarkdown@2.7:", type=("build", "run"))
	depends_on("r-tibble", type=("build", "run"))
	depends_on("r-tidyr", type=("build", "run"))
	depends_on("r-truncnorm", type=("build", "run"))
	depends_on("r-viridislite", type=("build", "run"))
	depends_on("r-withr", type=("build", "run"))
