# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RDchipio(RPackage):
	"""Methods for Reading dChip Files

	Functions for reading DCP and CDF.bin files generated by the dChip software.
	"""
	
	homepage = "https://github.com/HenrikBengtsson/dChipIO"
	cran = "dChipIO" 

	version("0.1.5", md5="165cd48cf99b8647f88de361d633786d")

	depends_on("r@2.6:", type=("build", "run"))
