# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RMpranalyze(RPackage):
	"""Statistical Analysis of MPRA data

	MPRAnalyze provides statistical framework for the analysis of data generated by Massively Parallel Reporter Assays (MPRAs), used to directly measure enhancer activity. MPRAnalyze can be used for quantification of enhancer activity, classification of active enhancers and comparative analyses of enhancer activity between conditions. MPRAnalyze construct a nested pair of generalized linear models (GLMs) to relate the DNA and RNA observations, easily adjustable to various experimental designs and conditions, and provides a set of rigorous statistical testig schemes.
	"""
	
	homepage = "https://github.com/YosefLab/MPRAnalyze"
	bioc = "MPRAnalyze"

	version("1.26.0", commit="97c52b070b1182dac2e3927b08b77b642a1e2fb3")
	version("1.20.0", commit="dcb9ac427e152f6e1e9716c45d1b242463ddbc44")

	depends_on("r-biocparallel", type=("build", "run"))
	depends_on("r-progress", type=("build", "run"))
	depends_on("r-summarizedexperiment", type=("build", "run"))
