# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RGgoceanmaps(RPackage):
	"""Plot Data on Oceanographic Maps using 'ggplot2'

	Allows plotting data on bathymetric maps using 'ggplot2'. Plotting
  oceanographic spatial data is made as simple as feasible, but also flexible
  for custom modifications. Data that contain geographic information from 
  anywhere around the globe can be plotted on maps generated by the basemap()
  or qmap() functions using 'ggplot2' layers separated by the '+' operator. The 
  package uses spatial shape- ('sf') and raster ('stars') files, geospatial 
  packages for R to manipulate, and the 'ggplot2' package to plot these 
  files. The package ships with low-resolution spatial data files and 
  higher resolution files for detailed maps are stored in the 
  'ggOceanMapsLargeData' repository on GitHub and downloaded automatically 
  when needed. 
	"""
	
	homepage = "https://mikkovihtakari.github.io/ggOceanMaps/"
	cran = "ggOceanMaps" 

	version("2.2.0", md5="93f1d9518f3475417a309bbc1bbf4386")

	depends_on("r@3.5:", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-sf", type=("build", "run"))
	depends_on("r-stars", type=("build", "run"))
	depends_on("r-smoothr", type=("build", "run"))
	depends_on("r-units", type=("build", "run"))
