# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RGitgpt(RPackage):
	"""Automated Git Commit Messages using the 'OpenAI' 'GPT' Model

	Automates the process of adding,
    committing, and pushing changes to a 'git' repository
    using commit messages generated by passing the git diff output 
    to the 'OpenAI'
    'GPT-3.5 Turbo' model (<https://platform.openai.com/docs/models/gpt-3>). 
	"""
	
	homepage = "https://github.com/stevecondylios/gitGPT"
	cran = "gitGPT" 

	version("0.1.3", md5="3a803d0b9c557c2d1a69de3bb51ebadb")

	depends_on("r-httr", type=("build", "run"))
	depends_on("r-jsonlite", type=("build", "run"))
