# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RRemla(RPackage):
	"""Robust Expectation-Maximization Estimation for Latent Variable
Models

	Traditional latent variable models assume that the population
    is homogeneous, meaning that all individuals in the population are
    assumed to have the same latent structure. However, this assumption is
    often violated in practice given that individuals may differ in their
    age, gender, socioeconomic status, and other factors that can affect
    their latent structure. The robust expectation maximization (REM)
    algorithm is a statistical method for estimating the parameters of a
    latent variable model in the presence of population heterogeneity as recommended by 
    Nieser & Cochran (2023) <doi:10.1037/met0000413>. The REM algorithm is based on the
    expectation-maximization (EM) algorithm, but it allows for the case
    when all the data are generated by the assumed data generating model.
	"""
	
	homepage = "https://github.com/knieser/REM"
	cran = "REMLA" 

	version("1.0", md5="9347d3c09ca58b1e6366808dc927e61b")

	depends_on("r-gparotation", type=("build", "run"))
	depends_on("r-geex", type=("build", "run"))
