# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RIdslCsa(RPackage):
	"""Composite Spectra Analysis (CSA) for High-Resolution Mass
Spectrometry Analyses

	A fragmentation spectra detection pipeline for high-throughput LC/HRMS data processing using peaklists generated by the 'IDSL.IPA' workflow <doi:10.1021/acs.jproteome.2c00120>. The 'IDSL.CSA' package can deconvolute fragmentation spectra from Composite Spectra Analysis (CSA), Data Dependent Acquisition (DDA) analysis, and various Data-Independent Acquisition (DIA) methods such as MS^E, All-Ion Fragmentation (AIF) and SWATH-MS analysis. The 'IDSL.CSA' package was introduced in <doi:10.1021/acs.analchem.3c00376>.
	"""
	
	homepage = "https://github.com/idslme/idsl.csa"
	cran = "IDSL.CSA" 

	version("1.2", md5="92c03f96d66ec442ef0cccf4e5134df9")

	depends_on("r@4:", type=("build", "run"))
	depends_on("r-idsl-mxp", type=("build", "run"))
	depends_on("r-idsl-ipa", type=("build", "run"))
	depends_on("r-idsl-fsa", type=("build", "run"))
	depends_on("r-readxl", type=("build", "run"))
