# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RRmss(RPackage):
	"""Robust Multi-Model Subset Selection

	Efficient algorithms for generating ensembles of robust, sparse and diverse models via robust 
             multi-model subset selection (RMSS). The robust ensembles are generated by minimizing the sum of 
             the least trimmed square loss of the models in the ensembles under constraints  for the size of 
             the models and the sharing of the predictors. Tuning parameters for the robustness, sparsity and
             diversity of the robust ensemble are selected by cross-validation.
	"""
	
	cran = "RMSS" 

	version("1.1.1", md5="f874f17e9e9c17324bf05af659f3a639")

	depends_on("r-rcpp", type=("build", "run"))
	depends_on("r-srlars", type=("build", "run"))
	depends_on("r-robstepsplitreg", type=("build", "run"))
	depends_on("r-cellwise", type=("build", "run"))
	depends_on("r-robustbase", type=("build", "run"))
	depends_on("r-rcpparmadillo", type=("build", "run"))
