# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RDirExpiry(RPackage):
	"""Managing Expiration for Cache Directories.

	Implements an expiration system for access to versioned directories.
	Directories that have not been accessed by a registered function within a
	certain time frame are deleted. This aims to reduce disk usage by
	eliminating obsolete caches generated by old versions of packages."""

	bioc = "dir.expiry"
	urls = ["https://www.bioconductor.org/packages/release/bioc/src/contrib/dir.expiry_1.10.0.tar.gz", "https://www.bioconductor.org/packages/release/bioc/src/contrib/Archive/dir.expiry/dir.expiry_1.10.0.tar.gz"]

	version("1.10.0", md5="ddefb728416ca4283805e19a898e9245")

	depends_on("r-filelock", type=("build", "run"))
