# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RDartrPopgen(RPackage):
	"""Analysing 'SNP' and 'Silicodart' Data Generated by Genome-Wide
Restriction Fragment Analysis

	Facilitates the analysis of SNP (single nucleotide polymorphism) 
    and silicodart (presence/absence) data. 'dartR.popgen' provides a suit of 
    functions to analyse such data in a population genetics context. It provides
    several functions to calculate population genetic metrics and to study 
    population structure. Quite a few functions need additional software to be 
    able to run (gl.run.structure(), gl.blast(), gl.LDNe()). You find detailed description 
    in the help pages how to download and link the packages so the function can 
    run the software. 'dartR.popgen' is part of the the 'dartRverse' suit of packages.
    Gruber et al. (2018) <doi:10.1111/1755-0998.12745>.
    Mijangos et al. (2022) <doi:10.1111/2041-210X.13918>.
	"""
	
	homepage = "https://green-striped-gecko.github.io/dartR/"
	cran = "dartR.popgen" 

	version("0.32", md5="d66d957d26bb6c1175a0c5b551e2121b")

	depends_on("r@3.5:", type=("build", "run"))
	depends_on("r-adegenet@2:", type=("build", "run"))
	depends_on("r-dartr-base", type=("build", "run"))
	depends_on("r-dartr-data", type=("build", "run"))
	depends_on("r-mass", type=("build", "run"))
	depends_on("r-dplyr", type=("build", "run"))
	depends_on("r-patchwork", type=("build", "run"))
	depends_on("r-crayon", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-data-table", type=("build", "run"))
	depends_on("r-stringr", type=("build", "run"))
