# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RCryptrndtest(RPackage):
	"""Statistical Tests for Cryptographic Randomness

	Performs cryptographic randomness tests on a sequence of random
    integers or bits. Included tests are greatest common divisor, birthday spacings,
    book stack, adaptive chi-square, topological binary, and three random walk
    tests (Ryabko and Monarev, 2005) <doi:10.1016/j.jspi.2004.02.010>. Tests except greatest common divisor and birthday spacings are not
    covered by standard test suites. In addition to the chi-square goodness-of-fit
    test, results of Anderson-Darling, Kolmogorov-Smirnov, and Jarque-Bera tests are
    also generated by some of the cryptographic randomness tests.
	"""
	
	cran = "CryptRndTest" 

	version("1.2.7", md5="ad0bb0157a9b60774360d9a58da1d4bf")

	depends_on("r-ksamples", type=("build", "run"))
	depends_on("r-sfsmisc", type=("build", "run"))
	depends_on("r-rmpfr", type=("build", "run"))
	depends_on("r-lambertw", type=("build", "run"))
	depends_on("r-gmp", type=("build", "run"))
	depends_on("r-tseries", type=("build", "run"))
