from spack.package import *


class PySqanti3(Package):
    """SQANTI3 characterizes and filters long-read transcriptomes."""

    homepage = "https://github.com/ConesaLab/SQANTI3"
    url = "https://github.com/ConesaLab/SQANTI3/archive/refs/tags/v5.3.0.tar.gz"
    git = "https://github.com/ConesaLab/SQANTI3.git"

    license("GPL-3.0-only")

    version("6.0", sha256="7703da9acca51150d4e1ab9def8bf1cd37e507a760a9a5259b9cd9b8be1fd3fa")
    version("5.3.0", sha256="fcb53fd2ead6bdfdd69777cb95fc704d36456a89b23d73f4600ebf0db786c2e1")

    depends_on("python@3.11:3.11", type=("build", "run"), when="@6.0:")
    depends_on("python@3.7:3.11", type=("build", "run"), when="@:5")
    depends_on("py-argcomplete", type=("build", "run"))
    depends_on("py-argh", type=("build", "run"), when="@6.0:")
    depends_on("py-bcbio-gff", type=("build", "run"))
    depends_on("py-biopython@1.81:1.81", type=("build", "run"), when="@6.0:")
    depends_on("py-biopython", type=("build", "run"), when="@:5")
    depends_on("bedtools2", type=("build", "run"), when="@6.0:")
    depends_on("py-bx-python", type=("build", "run"))
    depends_on("py-cython@3:", type=("build", "run"), when="@6.0:")
    depends_on("py-cython", type=("build", "run"), when="@:5")
    depends_on("desalt", type=("build", "run"))
    depends_on("py-dill", type=("build", "run"), when="@6.0:")
    depends_on("gffread", type=("build", "run"))
    depends_on("gmap-gsnap", type=("build", "run"))
    depends_on("py-gffutils", type=("build", "run"), when="@6.0:")
    depends_on("py-gtftools", type=("build", "run"))
    depends_on("py-importlib-metadata", type=("build", "run"), when="@6.0:")
    depends_on("py-intervaltree", type=("build", "run"), when="@6.0:")
    depends_on("py-jinja2", type=("build", "run"), when="@6.0:")
    depends_on("py-jinja2", type=("build", "run"), when="@:5")
    depends_on("kallisto", type=("build", "run"), when="@6.0:")
    depends_on("kallisto", type=("build", "run"), when="@:5")
    depends_on("minimap2", type=("build", "run"), when="@6.0:")
    depends_on("minimap2", type=("build", "run"), when="@:5")
    depends_on("py-numpy@1.26:1", type=("build", "run"), when="@6.0:")
    depends_on("py-numpy", type=("build", "run"), when="@:5")
    depends_on("openssl", type=("build", "run"), when="@6.0:")
    depends_on("openssl", type=("build", "run"), when="@:5")
    depends_on("py-pandas@2.2:2", type=("build", "run"), when="@6.0:")
    depends_on("py-pandas", type=("build", "run"), when="@:5")
    depends_on("pandoc", type=("build", "run"), when="@6.0:")
    depends_on("pandoc", type=("build", "run"), when="@:5")
    depends_on("py-parasail", type=("build", "run"), when="@6.0:")
    depends_on("perl@5.32:5.32", type=("build", "run"), when="@6.0:")
    depends_on("perl", type=("build", "run"), when="@:5")
    depends_on("py-psutil@6.1:", type=("build", "run"), when="@6.0:")
    depends_on("py-psutil", type=("build", "run"), when="@:5")
    depends_on("py-pyarrow", type=("build", "run"), when="@6.0:")
    depends_on("py-pybedtools@0.10:", type=("build", "run"), when="@6.0:")
    depends_on("py-pybedtools", type=("build", "run"), when="@:5")
    depends_on("py-pyfaidx", type=("build", "run"), when="@6.0:")
    depends_on("py-pysam@0.22:0.22", type=("build", "run"), when="@6.0:")
    depends_on("py-pysam", type=("build", "run"), when="@:5")
    depends_on("py-pyyaml@6.0:", type=("build", "run"), when="@6.0:")
    depends_on("r@4.3.3:", type=("build", "run"), when="@6.0:")
    depends_on("r-biocmanager@1.30:", type=("build", "run"), when="@6.0:")
    depends_on("r-biocmanager", type=("build", "run"), when="@:5")
    depends_on("r-caret@6.0:", type=("build", "run"), when="@6.0:")
    depends_on("r-caret", type=("build", "run"), when="@:5")
    depends_on("r-dplyr@1.1:", type=("build", "run"), when="@6.0:")
    depends_on("r-dplyr", type=("build", "run"), when="@:5")
    depends_on("r-dt", type=("build", "run"), when="@6.0:")
    depends_on("r-dt", type=("build", "run"), when="@:5")
    depends_on("r-e1071@1.7:", type=("build", "run"), when="@6.0:")
    depends_on("r-e1071", type=("build", "run"), when="@:5")
    depends_on("r-forcats@1.0:", type=("build", "run"), when="@6.0:")
    depends_on("r-forcats", type=("build", "run"), when="@:5")
    depends_on("r-ggplot2@3.4:", type=("build", "run"), when="@6.0:")
    depends_on("r-ggplot2", type=("build", "run"), when="@:5")
    depends_on("r-ggplotify@0.1:", type=("build", "run"), when="@6.0:")
    depends_on("r-ggplotify", type=("build", "run"), when="@:5")
    depends_on("r-gridbase@0.4:", type=("build", "run"), when="@6.0:")
    depends_on("r-gridbase", type=("build", "run"), when="@:5")
    depends_on("r-gridextra@2.3:", type=("build", "run"), when="@6.0:")
    depends_on("r-gridextra", type=("build", "run"), when="@:5")
    depends_on("r-gviz", type=("build", "run"), when="@6.0:")
    depends_on("r-htmltools@0.5:", type=("build", "run"), when="@6.0:")
    depends_on("r-htmltools", type=("build", "run"), when="@:5")
    depends_on("r-jsonlite@1.8:", type=("build", "run"), when="@6.0:")
    depends_on("r-jsonlite", type=("build", "run"), when="@:5")
    depends_on("r-noiseq", type=("build", "run"))
    depends_on("r-optparse@1.7:", type=("build", "run"), when="@6.0:")
    depends_on("r-optparse", type=("build", "run"), when="@:5")
    depends_on("r-plotly@4.10:", type=("build", "run"), when="@6.0:")
    depends_on("r-plotly", type=("build", "run"), when="@:5")
    depends_on("r-plyr@1.8:", type=("build", "run"), when="@6.0:")
    depends_on("r-plyr", type=("build", "run"), when="@:5")
    depends_on("r-proc", type=("build", "run"))
    depends_on("r-purrr@1.0:", type=("build", "run"), when="@6.0:")
    depends_on("r-purrr", type=("build", "run"), when="@:5")
    depends_on("r-randomforest@4.7:", type=("build", "run"), when="@6.0:")
    depends_on("r-randomforest", type=("build", "run"), when="@:5")
    depends_on("r-readr@2.1:", type=("build", "run"), when="@6.0:")
    depends_on("r-readr", type=("build", "run"), when="@:5")
    depends_on("r-reshape@0.8:", type=("build", "run"), when="@6.0:")
    depends_on("r-reshape", type=("build", "run"), when="@:5")
    depends_on("r-rmarkdown", type=("build", "run"), when="@6.0:")
    depends_on("r-rmarkdown", type=("build", "run"), when="@:5")
    depends_on("r-scales@1.3:", type=("build", "run"), when="@6.0:")
    depends_on("r-scales", type=("build", "run"), when="@:5")
    depends_on("py-scipy@1.11:1.11", type=("build", "run"), when="@6.0:")
    depends_on("py-scipy", type=("build", "run"), when="@:5")
    depends_on("py-scikit-learn@1.5:1.5", type=("build", "run"), when="@6.0:")
    depends_on("py-scikit-learn", type=("build", "run"), when="@:5")
    depends_on("py-seaborn@0.13:", type=("build", "run"), when="@6.0:")
    depends_on("py-seaborn", type=("build", "run"), when="@:5")
    depends_on("seqtk@1.4:", type=("build", "run"), when="@6.0:")
    depends_on("seqtk", type=("build", "run"), when="@:5")
    depends_on("py-simplejson", type=("build", "run"), when="@6.0:")
    depends_on("py-sortedcontainers", type=("build", "run"), when="@6.0:")
    depends_on("star@2.7.11b", type=("build", "run"), when="@6.0:")
    depends_on("star", type=("build", "run"), when="@:5")
    depends_on("r-stringi@1.8:", type=("build", "run"), when="@6.0:")
    depends_on("r-stringi", type=("build", "run"), when="@:5")
    depends_on("r-stringr@1.5:", type=("build", "run"), when="@6.0:")
    depends_on("r-stringr", type=("build", "run"), when="@:5")
    depends_on("r-tibble@3.2:", type=("build", "run"), when="@6.0:")
    depends_on("r-tibble", type=("build", "run"), when="@:5")
    depends_on("r-tidyr@1.3:", type=("build", "run"), when="@6.0:")
    depends_on("r-tidyr", type=("build", "run"), when="@:5")
    depends_on("py-ultra-bioinformatics", type=("build", "run"))
    depends_on("py-zipp", type=("build", "run"), when="@6.0:")

    def install(self, spec, prefix):
        install_tree(".", prefix)
        mkdirp(prefix.bin)
        for script in ("sqanti3", "sqanti3_qc.py", "sqanti3_filter.py", "sqanti3_reads.py", "sqanti3_rescue.py"):
            set_executable(join_path(prefix, script))
            symlink(join_path(prefix, script), join_path(prefix.bin, script))

    def setup_run_environment(self, env):
        env.prepend_path("PYTHONPATH", self.prefix)
        env.prepend_path("PATH", self.prefix.bin)

    def install_test(self):
        with working_dir("spack-test", create=True):
            python = which(self.spec["python"].prefix.bin.python)
            python(join_path(self.prefix.bin, "sqanti3_qc.py"), "--help")
