# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RAnimalcules(RPackage):
    """Interactive microbiome analysis toolkit

    animalcules is an R package for utilizing up-to-date data analytics, visualization methods, and machine learning models to provide users an easy-to-use interactive microbiome analysis framework. It can be used as a standalone software package or users can explore their data with the accompanying interactive R Shiny application. Traditional microbiome analysis such as alpha/beta diversity and differential abundance analysis are enhanced, while new methods like biomarker identification are introduced by animalcules. Powerful interactive and dynamic figures generated by animalcules enable users to understand their data better and discover new insights.
    """

    homepage = "https://github.com/compbiomed/animalcules"
    bioc = "animalcules"

    version("1.24.0", commit="a290187cb1cf66f56715270303a1cb0755484139")
    version("1.18.3", commit="8e8e65869e6b3956eb185f1fff323b99d9ab609d")

    depends_on("r@4.3:", type=("build", "run"))
    depends_on("r-ape", type=("build", "run"))
    depends_on("r-assertthat", type=("build", "run"))
    depends_on("r-caret", type=("build", "run"))
    depends_on("r-covr", type=("build", "run"))
    depends_on("r-deseq2", type=("build", "run"))
    depends_on("r-dplyr", type=("build", "run"))
    depends_on("r-dt", type=("build", "run"))
    depends_on("r-forcats", type=("build", "run"))
    depends_on("r-ggplot2", type=("build", "run"))
    depends_on("r-ggforce", type=("build", "run"))
    depends_on("r-gunifrac", type=("build", "run"))
    depends_on("r-lattice", type=("build", "run"))
    depends_on("r-limma", type=("build", "run"))
    depends_on("r-magrittr", type=("build", "run"))
    depends_on("r-matrix", type=("build", "run"))
    depends_on("r-multiassayexperiment", type=("build", "run"))
    depends_on("r-plotly", type=("build", "run"))
    depends_on("r-rentrez", type=("build", "run"))
    depends_on("r-reshape2", type=("build", "run"))
    depends_on("r-rocit", type=("build", "run"))
    depends_on("r-s4vectors@0.23.19:", type=("build", "run"))
    depends_on("r-scales", type=("build", "run"))
    depends_on("r-shiny", type=("build", "run"))
    depends_on("r-shinyjs", type=("build", "run"))
    depends_on("r-summarizedexperiment", type=("build", "run"))
    depends_on("r-tibble", type=("build", "run"))
    depends_on("r-tsne", type=("build", "run"))
    depends_on("r-umap", type=("build", "run"))
    depends_on("r-vegan", type=("build", "run"))
    depends_on("r-xml", type=("build", "run"))
