# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RAntaresread(RPackage):
	"""Import, Manipulate and Explore the Results of an 'Antares'
Simulation

	Import, manipulate and explore results generated by 'Antares', a 
    powerful open source software developed by RTE (Réseau de Transport d’Électricité) to simulate and study electric power systems
    (more information about 'Antares' here : <https://antares-simulator.org/>).
	"""
	
	homepage = "https://github.com/rte-antares-rpackage/antaresRead"
	cran = "antaresRead" 

	version("2.6.0", md5="ad03cfb417ae63611315112307040c52")

	depends_on("r-data-table@1.9.6:", type=("build", "run"))
	depends_on("r-bit64", type=("build", "run"))
	depends_on("r-lubridate@1.7.1:", type=("build", "run"))
	depends_on("r-plyr", type=("build", "run"))
	depends_on("r-stringr", type=("build", "run"))
	depends_on("r-stringi", type=("build", "run"))
	depends_on("r-shiny", type=("build", "run"))
	depends_on("r-pbapply", type=("build", "run"))
	depends_on("r-doparallel", type=("build", "run"))
	depends_on("r-jsonlite", type=("build", "run"))
	depends_on("r-httr", type=("build", "run"))
	depends_on("r-memuse", type=("build", "run"))
	depends_on("r-purrr", type=("build", "run"))
