# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RExcursions(RPackage):
	"""Excursion Sets and Contour Credibility Regions for Random Fields

	Functions that compute probabilistic excursion sets, contour credibility regions, contour avoiding regions, and simultaneous confidence bands for latent Gaussian random processes and fields. The package also contains functions that calculate these quantities for models estimated with the INLA package. The main references for excursions are Bolin and Lindgren (2015) <doi:10.1111/rssb.12055>, Bolin and Lindgren (2017) <doi:10.1080/10618600.2016.1228537>, and Bolin and Lindgren (2018) <doi:10.18637/jss.v086.i05>. These can be generated by the citation function in R.
	"""
	
	homepage = "https://github.com/davidbolin/excursions"
	cran = "excursions" 

	version("2.5.8", md5="82db98a3ad7d59a82bd390eff17eeff0")

	depends_on("r@3.5:", type=("build", "run"))
	depends_on("r-matrix", type=("build", "run"))
	depends_on("r-sp", type=("build", "run"))
	depends_on("r-fmesher@0.1.2:", type=("build", "run"))
	depends_on("r-withr", type=("build", "run"))
	depends_on("gsl@2.1:", type=("build", "link", "run"))
