# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RHcadata(RPackage):
    """Accessing The Datasets Of The Human Cell Atlas in R/Bioconductor

    This package allows a direct access to the dataset generated by the Human Cell Atlas project for further processing in R and Bioconductor, in the comfortable format of SingleCellExperiment objects (available in other formats here: http://preview.data.humancellatlas.org/).
    """

    homepage = "https://github.com/federicomarini/HCAData"
    bioc = "HCAData"

    version("1.24.0", commit="08c299a6a454c275c251dd27ed245310d3d7e16b")
    version("1.18.0", commit="8aa4b68c5414775e43de4b7e74b0557db2933120")

    depends_on("r@3.6:", type=("build", "run"))
    depends_on("r-singlecellexperiment", type=("build", "run"))
    depends_on("r-experimenthub", type=("build", "run"))
    depends_on("r-annotationhub", type=("build", "run"))
    depends_on("r-hdf5array", type=("build", "run"))
