# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RWeightedzdiff(RPackage):
	"""Calculation of z-Differences

	Calculates z-differences (O.Kuss (2013) <doi:10.1016/j.jclinepi.2013.06.001>) for each variable scale (continuous, binary, ordinal and nominal) with or without weights (e.g. generated by propensity score methods).
	"""
	
	cran = "weightedZdiff" 

	version("0.1.0", md5="44ef94b48df12df5addca27d4532f64a")

	depends_on("r@2.10:", type=("build", "run"))
