# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RGlmDeploy(RPackage):
	"""'C' and 'Java' Source Code Generator for Fitted Glm Objects

	Provides two functions that generate source code implementing the predict 
  function of fitted glm objects. In this version, code can be generated for either 'C' 
  or 'Java'. The idea is to provide a tool for the easy and fast deployment of glm 
  predictive models into production. The source code generated by this package implements 
  two function/methods. One of such functions implements the equivalent to 
  predict(type="response"), while the second implements predict(type="link"). Source code 
  is written to disk as a .c or .java file in the specified path. In the case of c, an .h 
  file is also generated.
	"""
	
	homepage = "https://github.com/oscarcastrolopez/glm.deploy"
	cran = "glm.deploy" 

	version("1.0.4", md5="5234fe5cc757e0054ac66a0338040061")

	depends_on("r-rcpp", type=("build", "run"))
