# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RAntaresviz(RPackage):
	"""Antares Visualizations

	Visualize results generated by Antares, a powerful open source software
    developed by RTE to simulate and study electric power systems
    (more information about 'Antares' here: <https://github.com/AntaresSimulatorTeam/Antares_Simulator>).
    This package provides functions that create interactive charts to help
    'Antares' users visually explore the results of their simulations.
	"""
	
	homepage = "https://github.com/rte-antares-rpackage/antaresViz"
	cran = "antaresViz" 

	version("0.18.0", md5="a76e2bef33111f61e615402b7dbfb528")

	depends_on("r-antaresread@2.2.9:", type=("build", "run"))
	depends_on("r-antaresprocessing@0.13:", type=("build", "run"))
	depends_on("r-spmaps@0.5:", type=("build", "run"))
	depends_on("r-dygraphs@1.1.1.6:", type=("build", "run"))
	depends_on("r-shiny@0.13:", type=("build", "run"))
	depends_on("r-plotly@4.5.6:", type=("build", "run"))
	depends_on("r-htmltools", type=("build", "run"))
	depends_on("r-htmlwidgets@0.7:", type=("build", "run"))
	depends_on("r-manipulatewidget@0.10:", type=("build", "run"))
	depends_on("r-leaflet@1.1:", type=("build", "run"))
	depends_on("r-sp@2.0.0:", type=("build", "run"))
	depends_on("r-sf", type=("build", "run"))
	depends_on("r-webshot", type=("build", "run"))
	depends_on("r-data-table", type=("build", "run"))
	depends_on("r-lubridate", type=("build", "run"))
	depends_on("r-geojsonio", type=("build", "run"))
	depends_on("r-leaflet-minicharts@0.5.3:", type=("build", "run"))
	depends_on("r-assertthat", type=("build", "run"))
	depends_on("r-ramcharts", type=("build", "run"))
