# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RLcsm(RPackage):
	"""Univariate and Bivariate Latent Change Score Modelling

	Helper functions to implement univariate and bivariate latent change score models in R using the 'lavaan' package.
  For details about Latent Change Score Modeling (LCSM) see McArdle (2009) <doi:10.1146/annurev.psych.60.110707.163612> and Grimm, An, McArdle, Zonderman and Resnick (2012) <doi:10.1080/10705511.2012.659627>.
  The package automatically generates 'lavaan' syntax for different model specifications and varying timepoints.
  The 'lavaan' syntax generated by this package can be returned and further specifications can be added manually.
  Longitudinal plots as well as simplified path diagrams can be created to visualise data and model specifications.
  Estimated model parameters and fit statistics can be extracted as data frames.
  Data for different univariate and bivariate LCSM can be simulated by specifying estimates for model parameters to explore their effects.
  This package combines the strengths of other R packages like 'lavaan', 'broom', and 'semPlot' by generating 'lavaan' syntax that helps these packages work together.
	"""
	
	homepage = "https://milanwiedemann.github.io/lcsm/"
	cran = "lcsm" 

	version("0.3.2", md5="111068488b7fba704df89cf763852ec5")

	depends_on("r@3.5:", type=("build", "run"))
	depends_on("r-lavaan@0.6.2:", type=("build", "run"))
	depends_on("r-dplyr@0.7.4:", type=("build", "run"))
	depends_on("r-tibble@1.4.2:", type=("build", "run"))
	depends_on("r-magrittr@1.5:", type=("build", "run"))
	depends_on("r-rlang@0.1.6:", type=("build", "run"))
	depends_on("r-tidyr@0.8:", type=("build", "run"))
	depends_on("r-ggplot2@2.2.1:", type=("build", "run"))
	depends_on("r-broom@0.5.1:", type=("build", "run"))
	depends_on("r-semplot@1.1:", type=("build", "run"))
	depends_on("r-stringr@1.4:", type=("build", "run"))
	depends_on("r-purrr@0.3.4:", type=("build", "run"))
	depends_on("r-cli", type=("build", "run"))
