# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RNpsr(RPackage):
	"""Validate Instrumental Variables using NPS

	An R implementation of the Necessary and Probably Sufficient (NPS) test for finding valid instrumental variables, as suggested by Amit Sharma (2016, Working Paper) <http://amitsharma.in/pubs/necessary_probably_sufficient_iv_test.pdf>. The NPS test, compares the likelihood that a given set of observational data of the three variables Z, X and Y is generated by a valid instrumental variable model (Z -> X -> Y) to the likelihood that the data is generated by an invalid IV model.
	"""
	
	cran = "npsr" 

	version("0.1.1", md5="b6bfd26f382ff7d2472722cc4efb46e1")

	depends_on("r-infotheo", type=("build", "run"))
	depends_on("r-mass", type=("build", "run"))
	depends_on("r-gmp", type=("build", "run"))
