# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RKim(RPackage):
	"""A Toolkit for Behavioral Scientists

	A collection of functions for analyzing data typically collected 
    or used by behavioral scientists. Examples of the functions include
    a function that compares groups in a factorial experimental design,
    a function that conducts two-way analysis of variance (ANOVA),
    and a function that cleans a data set generated by Qualtrics surveys.
    Some of the functions will require installing additional package(s).
    Such packages and other references are cited within the section
    describing the relevant functions. Many functions in this package
    rely heavily on these two popular R packages:
    Dowle et al. (2021) <https://CRAN.R-project.org/package=data.table>.
    Wickham et al. (2021) <https://CRAN.R-project.org/package=ggplot2>.
	"""
	
	homepage = "https://github.com/jinkim3/kim"
	cran = "kim" 

	version("0.5.421", md5="a95ae80d529ccdf22f001dda767b816a")

	depends_on("r-data-table", type=("build", "run"))
	depends_on("r-remotes", type=("build", "run"))
