# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RAntaresprocessing(RPackage):
	"""'Antares' Results Processing

	
    Process results generated by 'Antares', a powerful open source software developed by
    RTE (Réseau de Transport d’Électricité) to simulate and study electric power systems (more information about
    'Antares' here: <https://github.com/AntaresSimulatorTeam/Antares_Simulator>).
    This package provides functions to create new columns like net load, load factors, upward and
    downward margins or to compute aggregated statistics like economic surpluses
    of consumers, producers and sectors.
	"""
	
	homepage = "https://github.com/rte-antares-rpackage/antaresProcessing"
	cran = "antaresProcessing" 

	version("0.18.1", md5="ea31e45c3cfb652b9fb9b20de3772f21")

	depends_on("r-antaresread@1.1.5:", type=("build", "run"))
	depends_on("r-data-table", type=("build", "run"))
