# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RTabulamurissenisdata(RPackage):
    """Bulk and single-cell RNA-seq data from the Tabula Muris Senis project

    This package provides access to RNA-seq data generated by the Tabula Muris Senis project via the Bioconductor project. The data is made available without restrictions by the Chan Zuckerberg Biohub. It is provided here without further processing, collected in the form of SingleCellExperiment objects.
    """

    homepage = "https://github.com/fmicompbio/TabulaMurisSenisData"
    bioc = "TabulaMurisSenisData"

    version("1.14.0", commit="6383b2275f4cd64a1ec854b4fe2e502af4804648")
    version("1.8.0", commit="962d71c4da3a3f6aded2355c6a783f332df49ebb")

    depends_on("r-experimenthub", type=("build", "run"))
    depends_on("r-singlecellexperiment", type=("build", "run"))
    depends_on("r-hdf5array", type=("build", "run"))
    depends_on("r-summarizedexperiment", type=("build", "run"))
    depends_on("r-gdata", type=("build", "run"))
    depends_on("r-annotationhub", type=("build", "run"))
