# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class ROfficedown(RPackage):
	"""Enhanced 'R Markdown' Format for 'Word' and 'PowerPoint'

	Allows production of 'Microsoft' corporate documents from 'R Markdown' by 
 reusing formatting defined in 'Microsoft Word' documents. You can reuse table styles, 
 list styles but also add column sections, landscape oriented pages. Table and image 
 captions as well as cross-references are transformed into 'Microsoft Word' fields, 
 allowing documents edition and merging without issue with references; the syntax 
 conforms to the 'bookdown' cross-reference definition. Objects generated by 
 the 'officer' package are also supported in the 'knitr' chunks. 
 'Microsoft PowerPoint' presentations also benefit from this as well as the 
 ability to produce editable vector graphics in 'PowerPoint' and also to 
 define placeholder where content is to be added.
	"""
	
	homepage = "https://ardata-fr.github.io/officeverse/"
	cran = "officedown" 

	version("0.3.1", md5="40f441c2105c139420c32caedbb4ba45")

	depends_on("r-knitr", type=("build", "run"))
	depends_on("r-rmarkdown", type=("build", "run"))
	depends_on("r-officer@0.5.1:", type=("build", "run"))
	depends_on("r-xml2", type=("build", "run"))
	depends_on("r-rlang", type=("build", "run"))
	depends_on("r-uuid", type=("build", "run"))
	depends_on("r-yaml", type=("build", "run"))
	depends_on("r-memoise", type=("build", "run"))
	depends_on("r-rvg@0.2.2:", type=("build", "run"))
	depends_on("pandoc@2.0:", type=("build", "link", "run"))
