# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RSemgram(RPackage):
	"""Extracting Semantic Motifs from Textual Data

	A framework for extracting semantic motifs around entities in textual data. It implements an entity-centered semantic grammar that distinguishes six classes of motifs: actions of an entity, treatments of an entity, agents acting upon an entity, patients acted upon by an entity, characterizations of an entity, and possessions of an entity. Motifs are identified by applying a set of extraction rules to a parsed text object that includes part-of-speech tags and dependency annotations - such as those generated by 'spacyr'. For further reference, see: Stuhler (2022) <doi: 10.1177/00491241221099551>.
	"""
	
	homepage = "https://github.com/omstuhler/semgram"
	cran = "semgram" 

	version("0.1.0", md5="35330a3fff883a537ab114c0d5b39f1d")

	depends_on("r@3.5.3:", type=("build", "run"))
	depends_on("r-data-table", type=("build", "run"))
	depends_on("r-rsyntax@0.1.2:", type=("build", "run"))
	depends_on("r-stringr", type=("build", "run"))
