# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RVisualpred(RPackage):
	"""Visualization 2D of Binary Classification Models

	Visual 2D point and contour plots for binary classification modeling under algorithms such as glm(), randomForest(), gbm(), nnet() and svm(), presented over two dimensions generated by FAMD and MCA methods. Package 'FactoMineR' for multivariate reduction functions and package 'MBA' for interpolation functions are used. The package can be used to visualize the discriminant power of input variables and algorithmic modeling, explore outliers, compare algorithm behaviour, etc. It has been created initially for teaching purposes, but it has also many practical uses.
	"""
	
	cran = "visualpred" 

	version("0.1.0", md5="2007390e00653877841d8a30fc1615db")

	depends_on("r@3.5:", type=("build", "run"))
	depends_on("r-gbm", type=("build", "run"))
	depends_on("r-randomforest", type=("build", "run"))
	depends_on("r-nnet@7.3.12:", type=("build", "run"))
	depends_on("r-e1071", type=("build", "run"))
	depends_on("r-mass@7.3.51.4:", type=("build", "run"))
	depends_on("r-magrittr", type=("build", "run"))
	depends_on("r-factominer@2.3:", type=("build", "run"))
	depends_on("r-ggplot2@3.3:", type=("build", "run"))
	depends_on("r-mltools", type=("build", "run"))
	depends_on("r-dplyr", type=("build", "run"))
	depends_on("r-data-table", type=("build", "run"))
	depends_on("r-mba", type=("build", "run"))
	depends_on("r-proc", type=("build", "run"))
	depends_on("r-ggrepel", type=("build", "run"))
