# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RDescrtab2(RPackage):
	"""Publication Quality Descriptive Statistics Tables

	Provides functions to create descriptive statistics tables for continuous and categorical variables.
    By default, summary statistics such as mean, standard deviation, quantiles, minimum and maximum for continuous
    variables and relative and absolute frequencies for categorical variables are calculated. 'DescrTab2' features a sophisticated algorithm to
    choose appropriate test statistics for your data and provides p-values. On top of this, confidence intervals for group
    differences of appropriated summary measures are automatically produces for two-group comparison.
    Tables generated by 'DescrTab2' can be integrated in a variety of document formats, including .html, .tex and .docx documents.
    'DescrTab2' also allows printing tables to console and saving table objects for later use.
	"""
	
	homepage = "https://imbi-heidelberg.github.io/DescrTab2/"
	cran = "DescrTab2" 

	version("2.1.16", md5="facf005488ffc39957c630c5ad81612c", url="https://cran.r-project.org/src/contrib/DescrTab2_2.1.16.tar.gz")

	depends_on("r@4:", type=("build", "run"))
	depends_on("r-nlme", type=("build", "run"))
	depends_on("r-exact2x2", type=("build", "run"))
	depends_on("r-desctools", type=("build", "run"))
	depends_on("r-dplyr", type=("build", "run"))
	depends_on("r-rlang", type=("build", "run"))
	depends_on("r-tibble", type=("build", "run"))
	depends_on("r-stringr", type=("build", "run"))
	depends_on("r-forcats", type=("build", "run"))
	depends_on("r-magrittr", type=("build", "run"))
	depends_on("r-scales", type=("build", "run"))
	depends_on("r-cli", type=("build", "run"))
	depends_on("r-kableextra", type=("build", "run"))
	depends_on("r-flextable@0.6.6:", type=("build", "run"))
	depends_on("r-officer", type=("build", "run"))
	depends_on("r-knitr", type=("build", "run"))
	depends_on("r-rmarkdown", type=("build", "run"))
	depends_on("r-haven", type=("build", "run"))
	depends_on("r-hmisc", type=("build", "run"))
