# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RTenxpbmcdata(RPackage):
	"""PBMC data from 10X Genomics

	Single-cell RNA-seq data for on PBMC cells, generated by 10X Genomics.
	"""
	
	bioc = "TENxPBMCData" 
	urls = ["https://www.bioconductor.org/packages/3.18/data/experiment/src/contrib/TENxPBMCData_1.20.0.tar.gz", "https://www.bioconductor.org/packages/3.18/data/experiment/src/contrib/Archive/TENxPBMCData/TENxPBMCData_1.20.0.tar.gz"]

	version("1.20.0", md5="3e6c961a01998667f37de542858dbc09")

	depends_on("r-singlecellexperiment", type=("build", "run"))
	depends_on("r-hdf5array", type=("build", "run"))
	depends_on("r-annotationhub", type=("build", "run"))
	depends_on("r-experimenthub", type=("build", "run"))

