# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RStatebins(RPackage):
	"""Create United States Uniform Cartogram Heatmaps

	The 'cartogram' heatmaps generated by the included methods 
    are an alternative to choropleth maps for the United States
    and are based on work by the Washington Post graphics department in their report
    on "The states most threatened by trade" 
    (<http://www.washingtonpost.com/wp-srv/special/business/states-most-threatened-by-trade/>).
    "State bins" preserve as much of the geographic placement of the states as 
    possible but have the look and feel of a traditional heatmap. Functions are 
    provided that allow for use of a binned, discrete scale, a continuous scale 
    or manually specified colors depending on what is needed for the underlying data.
	"""
	
	homepage = "https://gitlab.com/hrbrmstr/statebins"
	cran = "statebins" 

	version("1.4.0", md5="c6b4a8c68e70ce3c9a5dadde4081ad08")

	depends_on("r@3.5:", type=("build", "run"))
	depends_on("r-ggplot2@2.2.1:", type=("build", "run"))
	depends_on("r-scales@0.5:", type=("build", "run"))
