# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RTcpl(RPackage):
	"""ToxCast Data Analysis Pipeline

	A set of tools for processing and modeling high-throughput and
    high-content chemical screening data. The package was developed for the
    the chemical screening data generated by the US EPA ToxCast program, but
    can be used for diverse chemical screening efforts.
	"""
	
	homepage = "https://github.com/USEPA/CompTox-ToxCast-tcpl"
	cran = "tcpl" 

	version("3.1.0", md5="06bdacce1462858beb7b1a2ec951958c")

	depends_on("r@3.5:", type=("build", "run"))
	depends_on("r-data-table@1.9.4:", type=("build", "run"))
	depends_on("r-dbi", type=("build", "run"))
	depends_on("r-rmariadb", type=("build", "run"))
	depends_on("r-numderiv", type=("build", "run"))
	depends_on("r-rcolorbrewer", type=("build", "run"))
	depends_on("r-sqldf", type=("build", "run"))
	depends_on("r-dplyr", type=("build", "run"))
	depends_on("r-tidyr", type=("build", "run"))
	depends_on("r-plotly", type=("build", "run"))
	depends_on("r-tcplfit2", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-gridextra", type=("build", "run"))
	depends_on("r-stringr", type=("build", "run"))
