# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RAhmeshdbs(RPackage):
	"""MeSHDbs for AnnotationHub

	Supplies AnnotationHub with `MeSHDb` NIH MeSH annotation databases for many species. All the SQLite files and metadata.csv are generated by our Snakemake workflow [mesh-workflow](https://github.com/rikenbit/mesh-workflow).
	"""
	
	bioc = "AHMeSHDbs"

	version("1.8.0", commit="922356d5d0d79d9750a98a021e8e343811d5d26d")
	version("1.7.0", sha256="02f1bea88d9288b0693e2ea76c46cead98ed67e96a57339232fbadfdbb98b143")

	depends_on("r@4.1:", type=("build", "run"))
	depends_on("r-annotationhub@2.22:", type=("build", "run"))

