# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RAhmeshdbs(RPackage):
	"""MeSHDbs for AnnotationHub

	Supplies AnnotationHub with `MeSHDb` NIH MeSH annotation databases for many species. All the SQLite files and metadata.csv are generated by our Snakemake workflow [mesh-workflow](https://github.com/rikenbit/mesh-workflow).
	"""
	
	bioc = "AHMeSHDbs" 
	urls = ["https://www.bioconductor.org/packages/3.18/data/annotation/src/contrib/AHMeSHDbs_1.7.0.tar.gz", "https://www.bioconductor.org/packages/3.18/data/annotation/src/contrib/Archive/AHMeSHDbs/AHMeSHDbs_1.7.0.tar.gz"]

	version("1.7.0", md5="9bbcae25794d2f854a122ba36a4e4c5c")

	depends_on("r@4.1:", type=("build", "run"))
	depends_on("r-annotationhub@2.22:", type=("build", "run"))

	# annotation