# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RColorramp2(RPackage):
	"""Generate Color Mapping Functions

	A color mapping is generated according to the break values and corresponding colors.
    Other colors are generated by interpolating in a certain color space. The functions were part
    of the 'circlize' package <https://CRAN.R-project.org/package=circlize>.
	"""
	
	homepage = "https://github.com/jokergoo/colorRamp2"
	cran = "colorRamp2" 

	version("0.1.0", md5="fa9f2a46612420970933cecf2afa83c1", url="https://cran.r-project.org/src/contrib/colorRamp2_0.1.0.tar.gz")

	depends_on("r@3:", type=("build", "run"))
	depends_on("r-colorspace", type=("build", "run"))
