# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RDep(RPackage):
	"""Differential Enrichment analysis of Proteomics data

	This package provides an integrated analysis workflow for robust and reproducible analysis of mass spectrometry proteomics data for differential protein expression or differential enrichment. It requires tabular input (e.g. txt files) as generated by quantitative analysis softwares of raw mass spectrometry data, such as MaxQuant or IsobarQuant. Functions are provided for data preparation, filtering, variance normalization and imputation of missing values, as well as statistical testing of differentially enriched / expressed proteins. It also includes tools to check intermediate steps in the workflow, such as normalization and missing values imputation. Finally, visualization tools are provided to explore the results, including heatmap, volcano plot and barplot representations. For scientists with limited experience in R, the package also contains wrapper functions that entail the complete analysis workflow and generate a report. Even easier to use are the interactive Shiny apps that are provided by the package.
	"""
	
	bioc = "DEP"

	version("1.30.0", commit="0ba4621fecd1b8c8cf9b46a0cfc61a7dc576ee67")
	version("1.24.0", commit="3eedbc955d2c6e7e5a60b094132d081184df5d42")

	depends_on("r@3.5:", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-dplyr", type=("build", "run"))
	depends_on("r-purrr", type=("build", "run"))
	depends_on("r-readr", type=("build", "run"))
	depends_on("r-tibble", type=("build", "run"))
	depends_on("r-tidyr", type=("build", "run"))
	depends_on("r-summarizedexperiment@1.11.5:", type=("build", "run"))
	depends_on("r-msnbase", type=("build", "run"))
	depends_on("r-limma", type=("build", "run"))
	depends_on("r-vsn", type=("build", "run"))
	depends_on("r-fdrtool", type=("build", "run"))
	depends_on("r-ggrepel", type=("build", "run"))
	depends_on("r-complexheatmap", type=("build", "run"))
	depends_on("r-rcolorbrewer", type=("build", "run"))
	depends_on("r-circlize", type=("build", "run"))
	depends_on("r-shiny", type=("build", "run"))
	depends_on("r-shinydashboard", type=("build", "run"))
	depends_on("r-dt", type=("build", "run"))
	depends_on("r-rmarkdown", type=("build", "run"))
	depends_on("r-assertthat", type=("build", "run"))
	depends_on("r-gridextra", type=("build", "run"))
	depends_on("r-imputelcmd", type=("build", "run"))
	depends_on("r-cluster", type=("build", "run"))
