# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RPmxtools(RPackage):
	"""Pharmacometric and Pharmacokinetic Toolkit

	Pharmacometric tools for common data analytical tasks; closed-form solutions for calculating concentrations at given 
    times after dosing based on compartmental PK models (1-compartment, 2-compartment and 3-compartment, covering infusions, zero- 
    and first-order absorption, and lag times, after single doses and at steady state, per Bertrand & Mentre (2008) 
    <http://lixoft.com/wp-content/uploads/2016/03/PKPDlibrary.pdf>); parametric simulation from NONMEM-generated parameter estimates 
    and other output; and parsing, tabulating and plotting results generated by Perl-speaks-NONMEM (PsN).
	"""
	
	homepage = "https://github.com/kestrel99/pmxTools"
	cran = "pmxTools" 

	version("1.3", md5="4b9b0e55eccb57a4ca4f58f38c256c46")

	depends_on("r@3.50:", type=("build", "run"))
	depends_on("r-patchwork", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-chron", type=("build", "run"))
	depends_on("r-xml2", type=("build", "run"))
	depends_on("r-dplyr@0.8.5:", type=("build", "run"))
	depends_on("r-tibble", type=("build", "run"))
	depends_on("r-gghalves", type=("build", "run"))
	depends_on("r-ggdist", type=("build", "run"))
	depends_on("r-scales", type=("build", "run"))
	depends_on("r-mass", type=("build", "run"))
	depends_on("r-stringr", type=("build", "run"))
	depends_on("r-pknca", type=("build", "run"))
	depends_on("r-magrittr", type=("build", "run"))
	depends_on("r-data-tree", type=("build", "run"))
