# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RAhlrbasedbs(RPackage):
    """LRBaseDbs for AnnotationHub

    Supplies AnnotationHub with `LRbaseDb` Ligand-Receptor annotation databases for many species. All the SQLite files are generated by our Snakemake workflow [lrbase-workflow](https://github.com/rikenbit/lrbase-workflow). For the details, see the README.md of lrbase-workflow.
    """

    bioc = "AHLRBaseDbs"

    version("1.8.0", commit="0ee3f5cc6d8dd2798cf2dc8222bd6829d3cc348a")
    version(
        "1.7.0",
        sha256="cf51e69b0c9177480a9745c5f08718dafb891c2bace18da3a5d0dbc1c2c66fd9",
    )

    depends_on("r@4.1:", type=("build", "run"))
    depends_on("r-annotationhub@2.22:", type=("build", "run"))
