# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RSnpfiltr(RPackage):
	"""Interactively Filter SNP Datasets

	Is designed to interactively and reproducibly visualize and filter SNP
	(single-nucleotide polymorphism) datasets. This R-based implementation of SNP
	and genotype filters facilitates 
	an interactive and iterative SNP filtering pipeline, which can be documented
	reproducibly via Rmarkdown. 'SNPfiltR' contains functions for visualizing 
	various quality and missing data metrics for a SNP dataset, and then filtering
	the dataset based on user specified cutoffs.
	All functions take 'vcfR' objects as input, which can easily be
	generated by reading standard vcf (variant call format) files into R using 
	the R package 'vcfR' (Knaus and Grünwald) (<doi:10.1111/1755-0998.12549>). 
	Each 'SNPfiltR' function can return a newly filtered vcfR object, which can then be
	written to a local directory in standard vcf format using the 'vcfR' package,
	for downstream population genetic and phylogenetic analyses.
	"""
	
	cran = "SNPfiltR" 

	version("1.0.1", md5="e0285af58162d214229e47e26e1c11f0")

	depends_on("r@2.10:", type=("build", "run"))
	depends_on("r-vcfr", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-rtsne", type=("build", "run"))
	depends_on("r-cluster", type=("build", "run"))
	depends_on("r-adegenet", type=("build", "run"))
	depends_on("r-gridextra", type=("build", "run"))
	depends_on("r-ggridges", type=("build", "run"))
	depends_on("zlib", type=("build", "link", "run"))
