# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class ROtusummary(RPackage):
	"""Summarizing OTU Table Regarding the Composition, Abundance and
Beta Diversity of Abundant and Rare Biospheres

	Summarizes the taxonomic composition, diversity contribution of the rare and abundant community by using OTU (operational taxonomic unit) table which was generated by analyzing pipeline of 'QIIME' or 'mothur'. The rare biosphere in this package is subset by the relative abundance threshold (for details about rare biosphere please see Lynch and Neufeld (2015) <doi:10.1038/nrmicro3400>).
	"""
	
	homepage = "https://github.com/cam315/otuSummary"
	cran = "otuSummary" 

	version("0.1.2", md5="6eec13d55fe01812688f841873c05f90")

	depends_on("r@3.5:", type=("build", "run"))
	depends_on("r-reshape2@1.4:", type=("build", "run"))
