# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RBayespostest(RPackage):
	"""Generate Postestimation Quantities for Bayesian MCMC Estimation

	An implementation of functions to generate and plot postestimation quantities after estimating Bayesian regression models using Markov chain Monte Carlo (MCMC). Functionality includes the estimation of the Precision-Recall curves (see Beger, 2016 <doi:10.2139/ssrn.2765419>), the implementation of the observed values method of calculating predicted probabilities by Hanmer and Kalkan (2013) <doi:10.1111/j.1540-5907.2012.00602.x>, the implementation of the average value method of calculating predicted probabilities (see King, Tomz, and Wittenberg, 2000 <doi:10.2307/2669316>), and the generation and plotting of first differences to summarize typical effects across covariates (see Long 1997, ISBN:9780803973749; King, Tomz, and Wittenberg, 2000 <doi:10.2307/2669316>). This package can be used with MCMC output generated by any Bayesian estimation tool including 'JAGS', 'BUGS', 'MCMCpack', and 'Stan'.
	"""
	
	homepage = "https://github.com/ShanaScogin/BayesPostEst"
	cran = "BayesPostEst" 

	version("0.3.2", md5="0dc845b517b314832da96dbd67733a7a")

	depends_on("r@3.5:", type=("build", "run"))
	depends_on("r-cardata", type=("build", "run"))
	depends_on("r-catools", type=("build", "run"))
	depends_on("r-coda@0.13:", type=("build", "run"))
	depends_on("r-dplyr@0.5:", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-ggridges", type=("build", "run"))
	depends_on("r-reshape2", type=("build", "run"))
	depends_on("r-rlang", type=("build", "run"))
	depends_on("r-texreg", type=("build", "run"))
	depends_on("r-tidyr@0.5.1:", type=("build", "run"))
	depends_on("r-hdinterval", type=("build", "run"))
	depends_on("r-rocr", type=("build", "run"))
	depends_on("r-r2jags", type=("build", "run"))
	depends_on("r-runjags", type=("build", "run"))
	depends_on("r-rstanarm", type=("build", "run"))
	depends_on("r-rjags", type=("build", "run"))
	depends_on("r-mcmcpack", type=("build", "run"))
	depends_on("r-r2winbugs", type=("build", "run"))
	depends_on("r-brms", type=("build", "run"))
	depends_on("jags@4.3.0:", type=("build", "link", "run"))
