# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RRnaseqgeneedgerql(RPackage):
    """Gene-level RNA-seq differential expression and pathway analysis using Rsubread and the edgeR quasi-likelihood pipeline

    This workflow package provides, through its vignette, a complete case study analysis of an RNA-Seq experiment using the Rsubread and edgeR packages. The workflow starts from read alignment and continues on to data exploration, to differential expression and, finally, to pathway analysis. The analysis includes publication quality plots, GO and KEGG analyses, and the analysis of a expression signature as generated by a prior experiment.
    """

    homepage = "http://f1000research.com/articles/5-1438"
    bioc = "RnaSeqGeneEdgeRQL"

    version("1.32.0", commit="9b332127f19aabad9f43d903aaf73b19beb998f6")
    version("1.26.0", commit="a8984b6c5f0ea3d039b723042218d7023667ce67")

    depends_on("r@3.3:", type=("build", "run"))
    depends_on("r-edger", type=("build", "run"))
    depends_on("r-gplots", type=("build", "run"))
    depends_on("r-org-mm-eg-db", type=("build", "run"))
    depends_on("r-go-db", type=("build", "run"))
    depends_on("r-biocstyle", type=("build", "run"))
