# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RTaylorswift(RPackage):
	"""Color Palettes Generated by Taylor Swift Albums

	For when your colors absolutely should not be excluded from the narrative. 
	"""
	
	cran = "tayloRswift" 

	version("0.1.0", md5="f192b6856b2cff1d4e55fc0f46d3ccea")

