# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RWevid(RPackage):
	"""Quantifying Performance of a Binary Classifier Through Weight of
Evidence

	The distributions of the weight of evidence (log Bayes factor) favouring case over noncase status in a test dataset (or test folds generated by cross-validation) can be used to quantify the performance of a diagnostic test (McKeigue (2019), <doi:10.1177/0962280218776989>). The package can be used with any test dataset on which you have observed case-control status and have computed prior and posterior probabilities of case status using a model learned on a training dataset. To quantify how the predictor will behave as a risk stratifier, the quantiles of the distributions of weight of evidence in cases and controls can be calculated and plotted.
	"""
	
	homepage = "http://www.homepages.ed.ac.uk/pmckeigu/preprints/classify/wevidtutorial.html"
	cran = "wevid" 

	version("0.6.2", md5="6a9c96379ff657eda951f34e9f70af45")

	depends_on("r@2.10:", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-mclust", type=("build", "run"))
	depends_on("r-proc@1.9:", type=("build", "run"))
	depends_on("r-reshape2", type=("build", "run"))
	depends_on("r-zoo", type=("build", "run"))
