# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RSynthpop(RPackage):
	"""Generating Synthetic Versions of Sensitive Microdata for
Statistical Disclosure Control

	A tool for producing synthetic versions of microdata containing confidential information so that they are safe to be released to users for exploratory analysis. The key objective of generating synthetic data is to replace sensitive original values with synthetic ones causing minimal distortion of the statistical information contained in the data set. Variables, which can be categorical or continuous, are synthesised one-by-one using sequential modelling. Replacements are generated by drawing from conditional distributions fitted to the original data using parametric or classification and regression trees models. Data are synthesised via the function syn() which can be largely automated, if default settings are used, or with methods defined by the user. Optional parameters can be used to influence the disclosure risk and the analytical quality of the synthesised data. For a description of the implemented method see Nowok, Raab and Dibben (2016) <doi:10.18637/jss.v074.i11>.
	"""
	
	homepage = "https://www.synthpop.org.uk/"
	cran = "synthpop" 

	version("1.8-0", md5="8a89755606368efac15de8e171b0f35e")

	depends_on("r-lattice", type=("build", "run"))
	depends_on("r-mass", type=("build", "run"))
	depends_on("r-nnet", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-rpart", type=("build", "run"))
	depends_on("r-party", type=("build", "run"))
	depends_on("r-foreign", type=("build", "run"))
	depends_on("r-plyr", type=("build", "run"))
	depends_on("r-proto", type=("build", "run"))
	depends_on("r-polspline", type=("build", "run"))
	depends_on("r-randomforest", type=("build", "run"))
	depends_on("r-ranger", type=("build", "run"))
	depends_on("r-classint", type=("build", "run"))
	depends_on("r-mipfp", type=("build", "run"))
	depends_on("r-survival", type=("build", "run"))
	depends_on("r-stringr", type=("build", "run"))
	depends_on("r-rmutil", type=("build", "run"))
	depends_on("r-broman", type=("build", "run"))
