name: Spack Package Testing

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  test-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to enable diff
      
      - name: Get modified packages
        id: get-packages
        run: |
          # Get the diff and find modified files in packages/
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # For PRs, compare against the base branch
            MODIFIED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..HEAD)
          else
            # For pushes, compare against the previous commit
            MODIFIED_FILES=$(git diff --name-only HEAD~1..HEAD)
          fi
          
          echo "Modified files:"
          echo "$MODIFIED_FILES"
          
          # Extract package names from packages/* paths
          PACKAGES=$(echo "$MODIFIED_FILES" | grep '^packages/' | cut -d'/' -f2 | sort -u | tr '\n' ' ')
          
          echo "Modified packages: $PACKAGES"
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT

      - name: Debug network and server availability
        run: |
          echo "=== Network Debugging ==="
          echo "Checking server connectivity..."
          echo "MCP Server URL: ${{ vars.MCP_SERVER_URL }}"
          
          # Check if anything is listening on port 8000
          echo "Processes listening on port 8000:"
          netstat -tlnp | grep :8000 || echo "No processes found on port 8000"
          
          # Check if we can reach the MCP server
          echo "Testing MCP server connectivity..."
          curl -v --connect-timeout 5 ${{ vars.MCP_SERVER_URL }} 2>&1 || echo "Failed to connect to MCP server (Exit code: $?)"
          
          # Try host.docker.internal if the MCP server might be in a container
          echo "Testing host.docker.internal fallback..."
          curl -v --connect-timeout 5 http://host.docker.internal:8000 2>&1 || echo "host.docker.internal also failed"
          
          # Try localhost as another fallback
          echo "Testing localhost fallback..."
          curl -v --connect-timeout 5 http://127.0.0.1:8000 2>&1 || echo "localhost also failed"
          
          # List running processes to see if MCP server might be running
          echo "Looking for potential MCP server processes..."
          ps aux | grep -i mcp || echo "No MCP processes found"
          ps aux | grep -i spack || echo "No spack processes found"
          ps aux | grep -i python || echo "No python processes found"
          
          # Check for Docker containers that might be running the MCP server
          echo "Checking for Docker containers..."
          docker ps || echo "Docker not available or no containers running"

      - name: Test MCP server health endpoint
        continue-on-error: true
        run: |
          echo "Testing MCP server health endpoint..."
          RESPONSE=$(curl -s -L --connect-timeout 10 ${{ vars.MCP_SERVER_URL }}/health)
          echo "Health response: $RESPONSE"
          
          # Check if response contains expected values
          if echo "$RESPONSE" | grep -q '"status".*"healthy"' && echo "$RESPONSE" | grep -q '"service".*"softpack-mcp"'; then
            echo "✅ Health check passed"
          else
            echo "❌ Health check failed or server not available"
          fi
      
      - name: Process packages
        run: |
          PACKAGES="${{ steps.get-packages.outputs.packages }}"
          
          if [ -n "$PACKAGES" ]; then
            echo "Packages to process: $PACKAGES"
            
            # For now, just print the list of packages
            echo "The following packages were modified:"
            for package in $PACKAGES; do
              echo "  - $package"
            done
            
            # TODO: Add actual package installation/testing here
            # spack install $package
          else
            echo "No packages were modified in this commit"
          fi
