# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RMazealls(RPackage):
	"""Generate Recursive Mazes

	Supports the generation of parallelogram, equilateral
    triangle, regular hexagon, isosceles trapezoid, Koch snowflake,
    'hexaflake', Sierpinski triangle, Sierpinski carpet and Sierpinski
    trapezoid mazes via 'TurtleGraphics'. Mazes are generated by the recursive method:
    the domain is divided into sub-domains in which mazes are generated,
    then dividing lines with holes are drawn between them, see
    J. Buck, Recursive Division, <http://weblog.jamisbuck.org/2011/1/12/maze-generation-recursive-division-algorithm>.
	"""
	
	homepage = "https://github.com/shabbychef/mazealls"
	cran = "mazealls" 

	version("0.2.0", md5="15329b6582132e662ebf4a96381a0029")

	depends_on("r@3.0.2:", type=("build", "run"))
	depends_on("r-turtlegraphics", type=("build", "run"))
