# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class RDartrBase(RPackage):
	"""Analysing 'SNP' and 'Silicodart' Data - Basic Functions

	Facilitates the import and analysis of 'SNP' (single nucleotide 'polymorphism') 
    and 'silicodart' (presence/absence) data. The main focus is on data generated by 'DarT' 
    (Diversity Arrays Technology), however, data from other sequencing platforms can be used 
    once 'SNP' or related fragment presence/absence data from any source is imported. Genetic 
    datasets are stored in a derived 'genlight' format (package 'adegenet'), that allows for 
    a very compact storage of data and metadata. Functions are available for 
    importing and exporting of 'SNP' and 'silicodart' data, for reporting on and 
    filtering on various criteria (e.g. 'callrate', 'heterozygosity', 'reproducibility', 
    maximum allele frequency). Additional functions are available for visualization 
    (e.g. Principle Coordinate Analysis) and creating a spatial representation 
    using maps. 'dartR.base' is the 'base' package of the 'dartRverse' suits of packages. 
    To install the other packages, we recommend to install the 'dartRverse' package, that 
    supports the installation of all packages in the 'dartRverse'.
    If you want to cite 'dartR', you find the information by typing citation('dartR.base')
    in the console.
	"""
	
	homepage = "https://green-striped-gecko.github.io/dartR/"
	cran = "dartR.base" 

	version("0.65", md5="6c5fe9ac78119a2d109625ccf930ea2e")

	depends_on("r@3.5:", type=("build", "run"))
	depends_on("r-adegenet@2:", type=("build", "run"))
	depends_on("r-ggplot2", type=("build", "run"))
	depends_on("r-dplyr", type=("build", "run"))
	depends_on("r-dartr-data", type=("build", "run"))
	depends_on("r-ape", type=("build", "run"))
	depends_on("r-crayon", type=("build", "run"))
	depends_on("r-data-table", type=("build", "run"))
	depends_on("r-foreach", type=("build", "run"))
	depends_on("r-gridextra", type=("build", "run"))
	depends_on("r-patchwork", type=("build", "run"))
	depends_on("r-plyr", type=("build", "run"))
	depends_on("r-reshape2", type=("build", "run"))
	depends_on("r-snprelate", type=("build", "run"))
	depends_on("r-stampp", type=("build", "run"))
	depends_on("r-stringr", type=("build", "run"))
	depends_on("r-tidyr", type=("build", "run"))
	depends_on("r-mass", type=("build", "run"))
